import type {Metadata} from 'next';
import {anniversary as issue,anniversaryPageHref} from '../../../data/litecoin-anniversary';
import styles from './anniversary.module.css';
export const metadata:Metadata={title:'Litecoin at 15 · An 84-page LTC anniversary edition',description:'An independent, illustrated Litecoin anniversary edition: Charlie Lee, history, Foundation, MWEB, LitVM and the institutional notebook. Advance edition researched through October 4, 2026.'};
export default function AnniversaryLanding(){return <main className={styles.landing}>
 <div className={styles.breadcrumb}><a href="/conversations/">LTC Media / Special editions</a><span>01 · The anniversary collection</span></div>
 <section className={styles.hero}><a href={anniversaryPageHref(1)} className={styles.cover} aria-label="Open the 84-page Litecoin at 15 edition"><img src="/magazine/litecoin-15/cover.jpg" width="1024" height="1536" alt="Original conceptual illustration: a monumental silver timechain against a cobalt horizon." fetchPriority="high"/><div className={styles.coverWords} aria-hidden="true"><span>LTC MEDIA / THE ANNIVERSARY ISSUE</span><strong>Litecoin<br/>at 15.</strong><em>An open network.<br/>A shared future.</em><small>84 PAGES · ADVANCE EDITION<br/>Research through October 4, 2026</small></div></a><div className={styles.intro}><p className={styles.label}>84 pages. Fifteen years. One open invitation.</p><h1>A network.<br/>A family.<br/><em>A next chapter.</em></h1><p>The origin story. The people behind the code. The Foundation and the builders. A visual field guide to Litecoin, from its first public launch to the questions that matter now.</p><div className={styles.actions}><a href={anniversaryPageHref(1)}>Read the special edition →</a><a href={issue.pdf} download>Download all 84 pages ↓</a></div><a href="#contents">Explore the complete contents ↓</a><p className={styles.notice}><strong>Advance anniversary edition.</strong> Network anniversary: October 13, 2026. Planned cover date: October 15, 2026. Research stops October 4; later events are not reported as facts. Original AI-prepared features by AI Satoshi Ma; independent human editorial review is pending. Published independently by LTC Media, a Satnam Satoshi project. No Foundation affiliation, interview or endorsement is claimed.</p></div></section>
 <div className={styles.dates} aria-label="Edition dates"><div><strong>Oct 04</strong><span>2026 / Research cutoff</span></div><div><strong>Oct 13</strong><span>2026 / Fifteenth anniversary</span></div><div><strong>Oct 15</strong><span>2026 / Planned cover date</span></div></div>
 <section className={styles.contents} id="contents"><p className={styles.label}>The complete reading map</p><h2>Find your way into the story.</h2>{issue.chapters.map(chapter=><section className={styles.chapter} key={chapter.start}><h3>{chapter.title}<span>{String(chapter.start).padStart(2,'0')}–{chapter.end}</span></h3><ol className={styles.pageList} start={chapter.start}>{issue.pages.filter(p=>p.page>=chapter.start&&p.page<=chapter.end).map(p=><li key={p.page}><a href={anniversaryPageHref(p.page)}><span>{String(p.page).padStart(2,'0')}</span>{p.title}</a></li>)}</ol></section>)}</section>
 <section className={styles.artStrip} aria-label="Inside the illustrated edition"><figure><img src="/magazine/litecoin-15/origins.jpg" width="1536" height="1024" loading="lazy" alt="An imagined archive and silver bridge representing Litecoin’s open-source origins."/><figcaption><strong>The first fifteen years.</strong> A timeline with original records and short, attributed Charlie Lee quotations.</figcaption></figure><figure><img src="/magazine/litecoin-15/community.jpg" width="1536" height="1024" loading="lazy" alt="An illustrated world map with people sharing a working table."/><figcaption><strong>The next chapter belongs to the work.</strong> Foundation projects, technical explanations and a public invitation. Original conceptual artwork, not documentary photography.</figcaption></figure></section>
 </main>}
