import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {anniversary as issue,anniversaryBase,anniversaryPageHref,anniversarySources,type AnniversaryPage} from '../../../../data/litecoin-anniversary';
import styles from '../anniversary.module.css';
export function generateStaticParams(){return issue.pages.map(p=>({page:String(p.page)}))}
export async function generateMetadata({params}:{params:Promise<{page:string}>}):Promise<Metadata>{const {page}=await params;const p=issue.pages.find(p=>String(p.page)===page);return {title:`${p?.title??'Page'} · ${page}/84 · Litecoin at 15`,description:p?.dek}}
function Sources({p}:{p:AnniversaryPage}){return <details className={styles.sourceDetails}><summary>Read this page’s sources & dates ({p.sources.length})</summary><ol>{p.sources.map(id=>{const s=anniversarySources.get(id)!;return <li key={id}><a href={s.url}>[{s.number}] {s.title} ↗</a><span>{s.publisher} · {s.publishedDate?`Record date: ${s.publishedDate}`:'Publication date not supplied'} · Checked {s.checkedDate}</span></li>})}</ol><p>Source availability is not independent verification of an issuer’s claims. This page is an AI-prepared editorial preview; independent human review is pending.</p></details>}
export default async function AnniversaryReader({params}:{params:Promise<{page:string}>}){const {page}=await params;const p:AnniversaryPage|undefined=issue.pages.find(p=>String(p.page)===page);if(!p)notFound();const previous=issue.pages.find(x=>x.page===p.page-1),next=issue.pages.find(x=>x.page===p.page+1);
 return <main className={styles.reader}><nav className={styles.toolbar} aria-label="Special edition reader"><a href={`${anniversaryBase}#contents`}>← Contents</a><span>Litecoin at 15 / {p.page} of 84</span><a href={issue.pdf} download>84-page PDF ↓</a><details><summary>Jump to a page</summary><nav className={styles.jumpList} aria-label="Jump to magazine page">{issue.pages.map(x=><a key={x.page} href={anniversaryPageHref(x.page)} aria-current={p.page===x.page?'page':undefined}>{String(x.page).padStart(2,'0')} / {x.title}</a>)}</nav></details></nav>
 <article className={`${styles.sheet} ${p.page===1?styles.coverSheet:''} ${p.page===84?styles.backSheet:''}`} data-layout={p.layout} data-magazine-page={p.page}>
 {p.page===1?<div className={styles.cover}><img src={p.art!.src} alt={p.art!.alt} width="1024" height="1536" fetchPriority="high"/><div className={styles.coverWords}><span>LTC MEDIA / A SATNAM SATOSHI PUBLICATION</span><h1>Litecoin<br/>at 15.</h1><em>An open network.<br/>A shared future.</em><span>CHARLIE LEE · THE FOUNDATION · THE BUILDERS<br/>HISTORY · PRIVACY · INSTITUTIONAL QUESTIONS</span><small>84 PAGES / ADVANCE ANNIVERSARY EDITION<br/>Planned cover date October 15, 2026<br/>Research through October 4, 2026 · AI editorial preview</small></div></div>:<>
 <div className={styles.runningHead}><span>LTC / Litecoin at 15</span><span>{p.section}</span></div><header className={styles.pageHeader}><p className={styles.label}>{p.kicker}</p><h1>{p.title}</h1><p className={styles.dek}>{p.dek}</p></header>
 {p.quote&&<figure className={styles.quoteBand}><blockquote>“{p.quote.text}”</blockquote><figcaption><cite>{p.quote.person} · {p.quote.date}<br/><a href={anniversarySources.get(p.quote.sourceId)!.url}>Read the original source ↗</a></cite></figcaption></figure>}
 {p.art&&<figure className={`${styles.visual} ${styles.art}`}><img src={p.art.src} alt={p.art.alt} width="1536" height="1024" fetchPriority="high"/><figcaption>{p.art.caption}</figcaption></figure>}
 {p.diagram&&<figure className={`${styles.visual} ${styles.diagram}`}><img src={p.diagram.src} alt={`${p.diagram.labels.join(' → ')}. ${p.diagram.caption}`} width="1000" height="400"/><figcaption>{p.diagram.caption}</figcaption></figure>}
 <div className={styles.body}>{p.paragraphs.map((text,i)=><p key={i}>{text}</p>)}</div>
 {p.page===3&&<nav className={styles.indexLinks} aria-label="Chapter starts">{issue.chapters.map(c=><a key={c.start} href={anniversaryPageHref(c.start)}><span>PAGE {c.start}</span>{c.title} →</a>)}</nav>}
 {!p.sourcebook&&p.bullets.length>0&&<ul className={styles.bullets}>{p.bullets.map(text=><li key={text}>{text}</li>)}</ul>}
 {p.sourcebook?<ol className={styles.sourcebook}>{p.sources.map(id=>{const s=anniversarySources.get(id)!;return <li key={id}><strong>RECORD {String(s.number).padStart(2,'0')}</strong><a href={s.url}>{s.title} ↗</a><span>{s.publisher}<br/>{s.publishedDate?`Record date ${s.publishedDate}`:'Undated source'} · Checked {s.checkedDate}</span></li>})}</ol>:p.sources.length>0?<Sources p={p}/>:<p className={styles.readerNote}>Original editorial framework or invitation; diagrams are conceptual unless a dated quantity is explicitly identified.</p>}
 <footer className={styles.folio}><span>Advance edition / Research Oct 4, 2026</span><a href={`${anniversaryBase}#contents`}>LTC Media · 84 pages</a><strong>{String(p.page).padStart(2,'0')}</strong></footer></>}
 </article>
 <nav className={styles.pager} aria-label="Previous and next magazine page">{previous?<a href={anniversaryPageHref(previous.page)} rel="prev"><span>← Page {previous.page}</span>{previous.title}</a>:<a href={anniversaryBase}><span>← The collection</span>About this special edition</a>}{next?<a href={anniversaryPageHref(next.page)} rel="next"><span>Page {next.page} →</span>{next.title}</a>:<a href={`${anniversaryBase}#contents`}><span>Keep exploring →</span>Return to the contents</a>}</nav>
 <p className={styles.readerNote}>Independent LTC Media special edition by Satnam Satoshi. Prepared October 4, 2026 for a planned October 15 cover date. Litecoin’s network anniversary is October 13. AI Satoshi Ma is the AI editorial lead; independent human review is pending. No future events, project endorsement or financial recommendation are implied. <a href="https://github.com/Satnam-Satoshi/Satoshi-Langar/issues/new?title=Litecoin%20at%2015%20correction">Send a source or correction ↗</a></p>
 </main>}
