import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { editorialSpecials,specialArtwork,specialHref } from '../../../data/editorial-specials';
import styles from '../editorial.module.css';
export const dynamicParams=false;
export const generateStaticParams=()=>editorialSpecials.map(s=>({slug:s.slug}));
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const s=editorialSpecials.find(s=>s.slug===slug);return s?{title:`LTC · ${s.subject} · ${s.title}`,description:s.dek,alternates:{canonical:`https://ltcmagazine.org${specialHref(slug)}`},openGraph:{title:`${s.subject}: ${s.title}`,description:s.dek,images:[`https://ltcmagazine.org${specialArtwork(slug)}`]}}:{}}
export default async function SpecialPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const s=editorialSpecials.find(s=>s.slug===slug);if(!s)notFound();const other=editorialSpecials.find(x=>x.slug!==slug)!;
 return <main className={styles.reader} data-special={s.id}>
 <nav className={styles.topNav} aria-label="Special edition navigation"><a href="/conversations/">← LTC newsroom</a><a href="#contents">Contents ↓</a><a href="/conversations/archive/">Issue library ↗</a></nav>
 <header className={styles.cover}><img src={specialArtwork(slug)} width="1086" height="1448" alt="Original conceptual cover art; not a documentary photograph or data chart."/><div className={styles.coverText}><div className={styles.masthead}>LTC <span>LUNCH TIME<br/>CONVERSATIONS</span></div><p className={styles.kicker}>The independent special / October 2026</p><h1>{s.title}</h1><p className={styles.subject}>{s.subject}</p><p className={styles.coverDek}>{s.dek}</p><a className={styles.coverButton} href="#contents">Open the magazine ↓</a><p className={styles.coverFoot}>Open history. Original perspective. Public evidence.</p></div></header>
 <div className={styles.record}><span>{s.classification}</span><span>Research through {s.researchThrough}</span><span>{s.sections.length} chapters · Free to read</span></div>
 <section className={styles.opening}><p className={styles.kicker}>A note from the editorial desk</p><h2>{slug==='proof-of-people'?'Open money has a human story.':slug==='charlie-lee'?'A fork in the road. A life in the code.':'If you know, help someone else know.'}</h2><div>{s.intro.map(p=><p key={p}>{p}</p>)}<p className={styles.fine}>{s.byline}. AI-prepared and checked against the cited public record. This is an independently prepared publication, not an interview or an authorized biography. No endorsement or independent human fact-check is claimed.</p></div></section>
 <nav id="contents" className={styles.contents} aria-labelledby="contents-title"><div><p className={styles.kicker}>Your reading map</p><h2 id="contents-title">Follow your<br/><em>curiosity.</em></h2><p>Read in sequence or enter at the question that interests you. Each chapter returns to its evidence.</p><a href="#timeline">The timeline ↗</a><a href="#sources">The sourcebook ↗</a></div><ol>{s.sections.map((section,i)=><li key={section.id}><a href={`#${section.id}`}><span>{String(i+1).padStart(2,'0')}</span><div><small>{section.kicker.replace(/^\d+\s*·\s*/,'')}</small><strong>{section.title}</strong></div><span aria-hidden="true">↗</span></a></li>)}</ol></nav>
 <section id="timeline" className={styles.timeline}><p className={styles.kicker}>Context, in order</p><h2>Take the long view.</h2><ol>{s.timeline.map((event,i)=><li key={`${event.date}-${i}`}><time>{event.date}</time><p>{event.label}</p><div>{event.sourceIds.map(id=><a key={id} href={`#source-${id}`}>[{id}]</a>)}</div></li>)}</ol></section>
 {s.sections.map((section,i)=><section key={section.id} id={section.id} className={styles.chapter} data-tone={i%3}><div className={styles.chapterArt} aria-hidden="true"><span className={styles.chapterNumber}>{String(i+1).padStart(2,'0')}</span><svg viewBox="0 0 400 270"><circle cx="210" cy="125" r="90"/><circle cx="210" cy="125" r="65"/><path d={i%2?'M20 225L120 95 220 170 360 25':'M20 220Q100 20 210 125T380 45'}/><circle cx="210" cy="125" r="9"/><path d="M120 245h220M150 255h190"/></svg><span>{section.kicker.replace(/^\d+\s*·\s*/,'')}</span><small>Editorial motif · not a data chart</small></div><div className={styles.chapterBody}><p className={styles.kicker}>Chapter {String(i+1).padStart(2,'0')} / {section.kicker.replace(/^\d+\s*·\s*/,'')}</p><h2>{section.title}</h2>{section.paragraphs.map(p=><p key={p}>{p}</p>)}<aside className={styles.takeaway}><strong>Keep this thought</strong><p>{section.takeaway}</p></aside><div className={styles.chapterSources}><span>Read the evidence:</span>{section.sourceIds.map(id=><a key={id} href={`#source-${id}`}>{s.sources.find(source=>source.id===id)?.publisher??id} [{id}] ↗</a>)}</div><nav className={styles.chapterNav} aria-label={`Chapter ${i+1} reading links`}><a href="#contents">↑ Contents</a><a href={i<s.sections.length-1?`#${s.sections[i+1].id}`:'#sources'}>{i<s.sections.length-1?'Next chapter':'Open sourcebook'} →</a></nav></div></section>)}
 {s.quotes.length>0&&<section className={styles.voices}><p className={styles.kicker}>In his own words</p>{s.quotes.map(q=><figure key={q.text}><blockquote>“{q.text}”</blockquote><figcaption>{q.attribution} · <a href={`#source-${q.sourceId}`}>Original source ↗</a></figcaption></figure>)}</section>}
 <section id="sources" className={styles.sourcebook}><p className={styles.kicker}>The record behind the read</p><h2>Curiosity leaves a trail.</h2><p>Publication dates belong to the sources; checked dates describe our research. Historical records are not current operating guarantees.</p><ol>{s.sources.map(source=><li id={`source-${source.id}`} key={source.id}><span>{source.id}</span><div><h3><a href={source.url}>{source.title} ↗</a></h3><p>{source.publisher} · Published {source.publishedAt??'date not stated'} · Checked {source.checkedAt}</p><p>{source.note}</p></div></li>)}</ol><details><summary>Editorial scope, limits and corrections</summary><ul>{s.limits.map(p=><li key={p}>{p}</li>)}</ul><p>Prepared {s.preparedAt}. Record {s.id}. <a href="https://github.com/Satnam-Satoshi/Satoshi-Langar/issues/new?title=LTC%20special%20edition%20correction">Submit a correction with a source ↗</a></p></details></section>
 <footer className={styles.back}><p className={styles.kicker}>The back page / Keep the conversation open</p><h2>{slug==='proof-of-people'?'Find the work. Bring a question.':slug==='charlie-lee'?'A creator begins it. A community carries it.':'Now you know. Pass it on.'}</h2><p>Choose one chapter. Open its source. Explain what you learned to somebody who is just starting. That is a useful kind of proof of work.</p><div><a href={specialHref(other.slug)}>Read {other.title} ↗</a><a href="/conversations/specials/proof-of-birthday/">Proof of Birthday · 84 pages ↗</a><a href="/ecosystem/">Join the open table ↗</a></div><strong>LTC <small>MEDIA</small></strong></footer>
 </main>;
}
