import type { Metadata } from 'next';
import styles from '../magazine.module.css';
export const metadata: Metadata = {
  title: 'LTC · Global Bitcoin events',
  description: 'An October 1, 2026 source check of organizer-announced Bitcoin events, with dates, locations and direct official links. Attendance is not arranged.',
};
const checkedDate = 'October 1, 2026';
const events = [
  { name: 'Plan ₿ Forum', dates: 'October 23–24, 2026', start: '2026-10-23', end: '2026-10-24', region: 'Europe', location: 'Lugano, Switzerland', venue: 'Convention Centre / Palazzo dei Congressi, Villa Ciani and Ex-Asilo Ciani', url: 'https://planb.lugano.ch/planb-forum/', detail: 'The organizer lists a two-day forum with keynotes, panels and workshops. Check its current program for access, language and venue details.' },
  { name: 'Bitcoin Amsterdam', dates: 'November 5–6, 2026', start: '2026-11-05', end: '2026-11-06', region: 'Europe', location: 'Halfweg, Netherlands · Amsterdam area', venue: 'SugarFactory, Kristalpromenade 7, 1165 PD Halfweg', url: 'https://www.bitcoin.amsterdam/', detail: 'The 2026 organizer homepage announces two conference days at SugarFactory. The event name is Amsterdam; the listed venue address is in Halfweg.' },
  { name: 'Bitcoin Korea Conference', dates: 'November 7–8, 2026', start: '2026-11-07', end: '2026-11-08', region: 'Asia', location: 'Seoul, South Korea', venue: 'November 7: COEX. November 8: Korea Federation of Banks and Community House Masil.', url: 'https://www.bitcoinkoreaconference.com/en', detail: 'The organizer lists different venues for the two days. Consult its day-specific schedule and access information before making plans.' },
];
export default function EventsPage() {
  return <main className={styles.paper}>
    <nav className={styles.articleNav} aria-label="Magazine navigation"><a className={styles.articleBrand} href="/conversations/" aria-label="LTC magazine home">LTC</a><a href="/conversations/">The founding issue</a><a href="/meetups/">Local community gatherings →</a></nav>
    <header className={styles.articleHeader}><p className={styles.kicker}>Community & the world · Events desk</p><h1>Meet the people<br/>doing the work.</h1><p className={styles.dek}>A small, sourced window into the global Bitcoin calendar. Explore the organizer’s program, bring a good question, and keep room for a local gathering too.</p><div className={styles.articleMeta}><span>Sources checked {checkedDate}</span><span>AI-prepared directory · Human editorial review pending</span><span><strong>Organizer announced · Attendance not arranged</strong></span></div></header>
    <section aria-labelledby="announced-events"><div className={styles.sectionHead}><h2 id="announced-events">Upcoming as of October 1, 2026</h2><p>Three organizer announcements</p></div><p className={styles.small}>Local calendar dates are shown; exact session times are not inferred. This is a dated editorial snapshot, not a live or complete calendar. Organizers can change dates, venues and access conditions. No Satnam Satoshi delegation, sponsorship or partnership is announced.</p><ol className={styles.archiveList}>{events.map(event => <li key={event.name}><div><p className={styles.kicker}>{event.region}</p><p><time dateTime={event.start}>{event.dates}</time></p><p className={styles.small}>Source checked {checkedDate}</p></div><article><h2><a className={styles.headlineLink} href={event.url}>{event.name} ↗</a></h2><p><strong>{event.location}</strong></p><p>{event.venue}</p><p>{event.detail}</p><p className={styles.small}>Status: organizer announced, attendance not arranged.</p><a className={styles.readLink} href={event.url}>Read the official event page</a></article></li>)}</ol></section>
    <section className={styles.eventsDirectory} aria-labelledby="organizer-directory"><div className={styles.sectionHead}><h2 id="organizer-directory">Keep exploring</h2><p>Organizer directory · No dates confirmed here</p></div><div className={styles.readingShelf}><article><p className={styles.kicker}>Africa · Organizer website</p><h3><a href="https://afrobitcoin.org/">Africa Bitcoin Conference ↗</a></h3><p>A direct organizer reference for further discovery. We could not complete a direct page retrieval on {checkedDate}; this listing asserts no upcoming date or venue.</p></article><article><p className={styles.kicker}>Senegal · Organizer website</p><h3><a href="https://dakarbitcoindays.com/">Dakar Bitcoin Days ↗</a></h3><p>Explore the organizer’s information. Direct retrieval was unavailable in this check; event details must be confirmed at the source before being added to our dated calendar.</p></article><article><p className={styles.kicker}>Your neighborhood</p><h3><a href="/meetups/">Start at a shared table →</a></h3><p>A useful gathering can begin with a small lesson and an act of service. Propose a local meetup with a responsible human host; no travel is required.</p></article></div></section>
    <aside className={styles.tableQuestion}><h2>Before<br/>you go.</h2><div><p>Choose the conversation, then check the details.</p><small>Confirm the current venue, local schedule, access and accessibility, costs and cancellation terms with the organizer. LTC has not registered anyone, reserved a place or arranged travel.</small></div></aside>
    <footer className={styles.articleFoot}><p>Have an official event announcement to share? <a href="/join/?path=ltc">Contribute to the events desk</a> with its organizer URL, date, location and public contact. We list evidence, not anonymous event claims.</p><p><a href="/conversations/read/a-global-movement-needs-a-local-table/">Read: A global movement needs a local table</a> · <a href="/conversations/">Return to the magazine</a></p><p className={styles.small}>External event listings are informational, not endorsements or investment recommendations. Any future attendance or expenditure is a separate human decision.</p></footer>
  </main>;
}
