import { birthday as issue, birthdayBase, birthdayPageHref } from '../../../data/proof-of-birthday';
import styles from './birthday.module.css';
export const metadata = { title: 'Proof of Birthday · Litecoin at 15 · LTC Media', description: 'An 84-page anniversary magazine: Litecoin’s origins, community, merged mining, privacy, builders and the institutional record. Revised advance edition.' };
export default function BirthdayLanding() { return <main className={styles.landing}>
  <div className={styles.toolbar}><a href="/conversations/">← LTC Media</a><span>The anniversary collection / Revision 2</span><a href="/conversations/litecoin/research/2026-10-04/">The reading room ↗</a></div>
  <section className={styles.landingIntro}><a href={birthdayPageHref(1)} className={styles.landingCover} aria-label="Open Proof of Birthday, the 84-page edition"><img src={issue.pages[0].art!.src} alt={issue.pages[0].art!.alt} width="1024" height="1536" fetchPriority="high"/><div aria-hidden="true"><b>LTC</b><strong>Proof of<br/><i>Birthday.</i></strong><em>Litecoin at 15.</em><small>84 PAGES / ADVANCE ANNIVERSARY EDITION<br/>RESEARCH OCTOBER 4 · PLANNED COVER OCTOBER 15</small></div></a><div className={styles.landingCopy}><p className={styles.kicker}>Fifteen years. Still making blocks.</p><h1>A little silver.<br/>A lot of work.<br/><em>One big birthday.</em></h1><p>Meet the people behind Litecoin. Follow the code, the mining families, the privacy questions and the paper trail to Wall Street. Then discover what a community can make together.</p><div className={styles.actions}><a href={birthdayPageHref(1)}>Read the 84-page magazine →</a><a href={issue.pdf} download>Keep the print edition ↓</a></div><a href="#contents">Browse every page ↓</a><p className={styles.small}>An independent LTC Media publication by Satnam Satoshi. Network anniversary: October 13, 2026. Planned cover date: October 15. Research stops October 4; later events are not reported as facts. AI-prepared editorial preview, with independent human review pending. No Foundation, contributor or issuer endorsement is claimed.</p></div></section>
  <nav className={styles.topicIndex} aria-label="Key stories"><a href={birthdayPageHref(4)}>The milestone timeline</a><a href={birthdayPageHref(5)}>Origins</a><a href={birthdayPageHref(7)}>Charlie Lee</a><a href={birthdayPageHref(25)}>The Foundation</a><a href={birthdayPageHref(29)}>Merged mining</a><a href={birthdayPageHref(33)}>MWEB</a><a href={birthdayPageHref(54)}>Wall Street</a><a href={birthdayPageHref(59)}>Fidelity</a><a href={birthdayPageHref(63)}>Institutional snapshot</a><a href={birthdayPageHref(65)}>SEC &amp; CFTC</a><a href={birthdayPageHref(66)}>News &amp; politics</a><a href={birthdayPageHref(69)}>Satnam Satoshi</a><a href={birthdayPageHref(70)}>Langar</a><a href={birthdayPageHref(72)}>Kalakar.x</a></nav><section className={styles.landingContents} id="contents"><p className={styles.kicker}>84 pages / 84 million LTC</p><h2>A reading map for the whole family.</h2>{issue.chapters.map(chapter=><section key={chapter.start}><h3>{chapter.title}<span>{String(chapter.start).padStart(2,'0')}–{chapter.end}</span></h3><ol start={chapter.start}>{issue.pages.filter(p=>p.page>=chapter.start&&p.page<=chapter.end).map(p=><li key={p.page}><a href={birthdayPageHref(p.page)}><span>{String(p.page).padStart(2,'0')}</span>{p.title}</a></li>)}</ol></section>)}</section>
  <div className={styles.landingNote}><p><a href={`${birthdayBase}print/`}>Open the complete magazine in one continuous reading view →</a></p><p>Printed and web pages share their design. Readability comes first on small screens. This revision replaces the earlier public special. The <a href="/conversations/litecoin/research/2026-10-04/">companion reading room</a> holds the expanded LTCN timeline and community source links.</p><p>Satnam Satoshi’s Langar and Kalakar pages describe proposed pilots. The inscription chapter is a proposal: no NFT, token, wallet action or on-chain publication has been created.</p></div>
</main>; }
