import { PageIntro } from '../components/PageIntro';
const repo='https://github.com/Satnam-Satoshi/Satoshi-Langar';
const tasks = [
 ['Learn & welcome','Read one page. Tell us what was confusing, missing or welcoming.','First contribution: help a newcomer'],
 ['Serve with Langar','Help research a local need or draft a practical, respectful volunteer guide. No field pilot is scheduled yet.','Satoshi Langar: contribute an idea'],
 ['Create with Kalakar.x','Offer a story, illustration, translation or accessibility improvement. Keep authorship and permissions clear.','Kalakar.x: creative contribution'],
 ['Help the LTC newsroom','Check a primary source, review a data method or offer a careful explanation.','LTC: editorial contribution'],
 ['Host a Bitcoin meetup','Propose a welcoming local gathering with a responsible host. No event dates are confirmed yet.','Community: meetup proposal'],
 ['Teach Sikh Bitcoin','Review a beginner lesson, improve a glossary or offer a carefully checked translation.','Sikh Bitcoin: learning contribution'],
 ['Build the tools','Inspect the repository, reproduce the build, improve a page or propose a small fix.','Engineering: proposed contribution'],
 ['Contribute with an agent','Identify the human steward, task, permissions and review plan. Begin with a small, evidence-backed proposal.','Agent contribution: task proposal'],
];
export default function JoinPage() { return <main><PageIntro eyebrow="Join the beginning" title="Start with what you have." description="A little time, a useful question or a skill you want to share. No wallet, payment or technical background is needed to begin."/><section className="reading-content" style={{maxWidth:1080}}><p>Choose a path below. Each link opens a draft GitHub issue for you to review and post. GitHub requires an account to submit; your post will be public. You can explore and learn without signing in.</p><div className="task-grid" style={{marginTop:30}}>{tasks.map(([title,body,subject])=><article className="task-card" key={title}><h2>{title}</h2><p>{body}</p><a href={`${repo}/issues/new?title=${encodeURIComponent(subject)}&body=${encodeURIComponent('What I would like to help with:\n\nA small first step:\n\nTime I can offer (optional):\n\nPlease keep this public post free of private contact details and sensitive information.')}`}>Prepare a contribution →</a></article>)}</div><h2>Make it small. Make it useful.</h2><ol><li>Choose one task you can explain in a few sentences.</li><li>Describe the result and anything you need clarified.</li><li>Post your proposal, then follow the discussion for human review.</li></ol><p>Want to start without an account? Read the mission, sketch an idea or draft a translation offline. More community channels are being prepared; see the official channel directory. We do not want you to enter information into a form that nobody can receive.</p><p><a href="/connect/">Official channels</a> · <a href="/sikh-bitcoin/">Start learning without an account</a> · <a href="/agents/">Agent contribution guidance</a> · <a href="/privacy/">Privacy and public participation</a></p></section></main>; }
