import type { Metadata } from 'next';
import {notFound} from 'next/navigation';
import {communityArchive,communityArchiveHref,communityDate} from '../../../../data/community-wire';
import styles from '../../wire.module.css';
export function generateStaticParams(){return communityArchive.map(record=>({id:record.id}));}
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;const record=communityArchive.find(r=>r.id===id);return {title:record?`Community source check · ${record.snapshot.collectedAt}`:'Community record',description:'An immutable Litecoin community source-check record with original publication times, source availability and the saved record hash.'};}
export default async function CommunityRecord({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const index=communityArchive.findIndex(r=>r.id===id);if(index<0)notFound();const record=communityArchive[index];
 return <main className={styles.page}><header className={styles.section}><p className={styles.kicker}>LTC / A page in the record</p><h1>What the source check found.</h1><p>Collected <time dateTime={record.snapshot.collectedAt}>{record.snapshot.collectedAt}</time>. This saved check retains both successful records and gaps. It does not claim that every community announcement was collected.</p><a href="/conversations/community/#history">← Return to the Community Wire</a></header><section className={styles.section}><h2>The accepted records.</h2>{record.snapshot.items.length?record.snapshot.items.map(item=><article key={item.id}><p className={styles.kicker}>{item.sourceName}</p><h3><a href={item.url}>{item.title} ↗</a></h3><p>Original publication: <time dateTime={item.publishedAt}>{communityDate(item.publishedAt)} · {item.publishedAt}</time></p><p>A first-party project record. A new retrieval is not a new release or an independent software audit.</p></article>):<p>No items passed this check.</p>}</section><section className={styles.section}><h2>Sources and limits.</h2><dl className={styles.recordMeta}>{record.snapshot.sourceStatus.map(source=><div key={source.id}><dt>{source.sourceName}</dt><dd>{source.status==='collected'?'Collected':'Unavailable / not accepted'}</dd><dd>{source.checkedAt??'Not requested in this run'}</dd><dd>{source.errorCode??'No source error recorded'}</dd><dd><a href={source.url}>Original endpoint ↗</a></dd><dd className={styles.hash}>{source.sha256?`Response SHA-256: ${source.sha256}`:'No response hash recorded'}</dd></div>)}</dl><p>Hashes identify the saved bytes. They are not source signatures or proof that every claim is correct.</p><p className={styles.hash}>Record SHA-256: {record.sha256}</p><a href={`/data/ltc-community/${record.id}.json`}>Download this public source-check record (JSON) →</a></section><nav className={styles.recordFooter} aria-label="Source-check history">{communityArchive[index+1]&&<a href={communityArchiveHref(communityArchive[index+1].id)}>← Earlier check: {communityArchive[index+1].snapshot.collectedAt}</a>}{communityArchive[index-1]&&<a href={communityArchiveHref(communityArchive[index-1].id)}>Later check: {communityArchive[index-1].snapshot.collectedAt} →</a>}<a href="/conversations/community/">All community reading →</a></nav></main>;
}
