import { ProgramGrid } from './components/ProgramGrid';
export default function Home(){return <main>
<section className="launch-hero"><div className="launch-wrap hero-layout"><div><p className="launch-eyebrow"><span className="status-dot"/> An open invitation to build</p><h1>Many hands.<br/>One <em>humanity.</em></h1><p className="hero-description">Learn Bitcoin. Create freely. Serve together.<br/>A community of people and AI turning open technology into everyday acts of care.</p><div className="launch-actions"><a className="launch-button" href="/join/">Find your place ↗</a><a className="launch-text-link" href="/ecosystem/">Explore the ecosystem →</a></div><p className="hero-footnote">Rooted in seva. Inspired by Satoshi. Open to everyone.</p></div><div className="community-art" aria-hidden="true"><div className="art-orbit art-orbit-one"/><div className="art-orbit art-orbit-two"/><div className="art-center"><span>ਸੇਵਾ</span><strong>seva</strong><small>service, freely given</small></div><span className="art-label art-label-one">Human wisdom</span><span className="art-label art-label-two">Useful intelligence</span><span className="art-label art-label-three">A place for everyone</span><div className="art-caption">A common purpose. A thousand ways to help.</div></div></div></section>
<div className="principles-strip"><div className="launch-wrap"><span>Open source</span><span>Proof of work</span><span>Human dignity</span><span>Individual sovereignty</span><a href="/technology/">Our Nakamoto standard ↗</a></div></div>
<section className="launch-wrap story-section"><p className="launch-eyebrow">The thread that connects us</p><div className="story-layout"><h2>A better future starts<br/>with <em>an open table.</em></h2><div><p>Guru Nanak’s wisdom inspires equality, honest work and sharing. Satoshi’s work inspires systems people can verify and participate in. We bring those ideas into practical community life.</p><p>A learner becomes a builder. An artist makes the work visible. A kitchen brings neighbors together. AI helps with the details; people carry the responsibility.</p><a className="launch-text-link" href="/mission/">Read our story →</a></div></div></section>
<section className="project-section"><div className="launch-wrap"><div className="section-top"><div><p className="launch-eyebrow">Six ways in. One shared purpose.</p><h2>Find the work that calls you.</h2></div><p>Start with curiosity, a skill, or a little time.<br/>Each program strengthens the others.</p></div><ProgramGrid/></div></section>
<section className="launch-wrap story-section"><div className="learning-feature"><div><p className="launch-eyebrow">Sikh Bitcoin · Our open learning room</p><h2>You don’t need to own bitcoin<br/>to <em>understand it.</em></h2><p>Begin with money, keys and verification. Three tracks. 63 lessons. Plain-language foundations, protocol depth and practical sovereignty, at your own pace.</p><a className="launch-button" href="/sikh-bitcoin/">Start learning →</a></div><ol className="lesson-preview"><li><span>01</span><div><strong>Bitcoin, without the jargon</strong><small>What it is, what it isn’t, and what you can verify.</small></div></li><li><span>02</span><div><strong>Your keys. Your responsibility.</strong><small>Understand custody before making a transaction.</small></div></li><li><span>03</span><div><strong>From a sat to a shared meal</strong><small>Lightning, artists and community service.</small></div></li></ol></div></section>
<section className="magazine-feature"><div className="launch-wrap"><div className="section-top"><p className="launch-eyebrow">A Satnam Satoshi publication</p><span className="edition-label">Edition 001 · October 1, 2026</span></div><a className="magazine-masthead" href="/conversations/">Lunch Time<br/><em>Conversations.</em></a><div className="magazine-bottom"><p>Politics & policy. Blockchain analysis. Institutional research.<br/>Original reporting and analysis, with sources you can inspect.</p><a className="launch-text-link" href="/conversations/">Open the magazine ↗</a></div></div></section>
<section className="launch-wrap human-section"><p className="launch-eyebrow">Builders, Bitcoiners & AI projects</p><div className="story-layout"><h2>Bring your intelligence.<br/><em>Keep people at the heart.</em></h2><div><p>Help translate a lesson, review a source, improve a tool or plan a kitchen. Experienced Bitcoiners can make the next person’s first step easier.</p><p>Agent Sangat welcomes independent AI teams and open models. Every agent works within a defined task, permission limit and human review.</p><a className="launch-text-link" href="/partners/">Build with us →</a></div></div></section>
<section className="launch-invitation"><div className="launch-wrap"><p className="launch-eyebrow">You are early. You are welcome.</p><h2>Start small.<br/><em>Make something matter.</em></h2><p>No wallet, payment or technical background needed.<br/>Choose one useful contribution and build from there.</p><a href="/join/" className="launch-button">Find your first contribution ↗</a><div className="invitation-links"><a href="/roadmap/">Explore the roadmap →</a><a href="/donate/">Support the work →</a></div></div></section>
</main>}
