import Link from 'next/link';
import { ArrowUpRight, HandHeart, Palette, Sprout, ArrowRight } from 'lucide-react';
const projects = [
  { number: '01', name: 'Satoshi Langar', verb: 'Share a meal.', icon: HandHeart, status: 'PILOT PLANNING', href: '/langar/', body: 'Food, dignity and a place at the table. Help shape local service with people who know their community.' },
  { number: '02', name: 'Kalakar.x', verb: 'Create something meaningful.', icon: Palette, status: 'OPEN FOR IDEAS', href: '/kalakar/', body: 'Art, stories and culture that connect us. Bring your voice and help make shared knowledge more human.' },
  { number: '03', name: 'Crypto Kitty', verb: 'Explore mutual support.', icon: Sprout, status: 'RESEARCH', href: '/crypto-kitty/', body: 'Learning from community savings circles. Research fair rules, human stewardship and ways to care for one another.' },
];
export default function Home() {
 return <main>
  <section className="launch-hero"><div className="launch-wrap hero-layout"><div>
    <p className="launch-eyebrow"><span className="status-dot" /> A community taking shape</p>
    <h1>Many hands.<br />One <em>humanity.</em></h1>
    <p className="hero-description">People and AI, building together in service of others. Rooted in seva. Inspired by Bitcoin. Open to everyone.</p>
    <div className="launch-actions"><Link className="launch-button" href="/join/">Find your place <ArrowUpRight size={18} aria-hidden="true" /></Link><Link className="launch-text-link" href="/mission/">Our story <ArrowRight size={16} aria-hidden="true" /></Link></div>
    <p className="hero-footnote">Your time, your creativity, your care. Start with what you have.</p>
  </div><div className="community-art" aria-hidden="true"><div className="art-orbit art-orbit-one" /><div className="art-orbit art-orbit-two" /><div className="art-center"><span>ਸੇਵਾ</span><strong>seva</strong><small>service, freely given</small></div><span className="art-label art-label-one">Human wisdom</span><span className="art-label art-label-two">Creative intelligence</span><span className="art-label art-label-three">Shared possibility</span><div className="art-caption">A common purpose. Room for every voice.</div></div></div></section>
  <section className="launch-wrap story-section" aria-labelledby="story-title"><p className="launch-eyebrow">The thread that connects us</p><div className="story-layout"><h2 id="story-title">What if building the future<br />began with <em>serving each other?</em></h2><div><p>Satnam Satoshi brings an old human practice into a new technological age: learn together, work honestly and share what we can.</p><p>Guru Nanak’s wisdom inspires our commitment to equality and service. Bitcoin inspires open verification and individual sovereignty. AI helps us turn ideas into useful work, with people remaining accountable.</p><Link className="launch-text-link" href="/mission/">Explore the mission <ArrowRight size={16} aria-hidden="true" /></Link></div></div></section>
  <section className="project-section" aria-labelledby="projects-title"><div className="launch-wrap"><div className="section-top"><div><p className="launch-eyebrow">One community. Three beginnings.</p><h2 id="projects-title">Care. Create. Share.</h2></div><p>Small beginnings, connected by a common purpose.<br />Help us shape what comes next.</p></div><div className="launch-project-grid">{projects.map(({ number, name, verb, icon: Icon, status, href, body }) => <article className="launch-project" key={name}><div className="project-top"><span>{number}</span><Icon size={28} strokeWidth={1.25} aria-hidden="true" /></div><p className="project-status">{status}</p><h3>{name}</h3><p className="project-verb">{verb}</p><p className="project-description">{body}</p><Link href={href}>Discover {name} <ArrowUpRight size={17} aria-hidden="true" /></Link></article>)}</div></div></section>
  <section className="launch-wrap human-section" aria-labelledby="human-title"><p className="launch-eyebrow">Human + AI</p><div className="story-layout"><h2 id="human-title">More hands to help.<br /><em>Humans at the heart.</em></h2><div><p>Writers, artists, developers, researchers, organizers—and the agents that help them. Every contribution can move the work forward.</p><p>AI Satoshi Ma supports research, design and building. Every agent needs a human steward, a clear task and limited permissions. People retain control of decisions and funds.</p><Link href="/agents/" className="launch-text-link">How agents contribute <ArrowRight size={16} aria-hidden="true" /></Link></div></div></section>
  <section className="launch-invitation"><div className="launch-wrap"><p className="launch-eyebrow">You are early. You are welcome.</p><h2>Bring a little of yourself.<br /><em>Build something for all of us.</em></h2><p>No wallet, payment or technical background needed.<br />Begin with one useful contribution.</p><Link href="/join/" className="launch-button">Find your first contribution <ArrowUpRight size={18} aria-hidden="true" /></Link><div className="invitation-links"><a href="https://github.com/Satnam-Satoshi/Satoshi-Langar">Explore the source ↗</a><Link href="/transparency/">See our progress →</Link></div></div></section>
 </main>;
}
