import styles from '../join/join.module.css';

export const metadata = { title: 'Your first-step plan · The open table', description: 'Review your personal contribution draft, open the relevant guide, download your plan and choose whether to share a public proposal.' };

export default function Welcome() {
  return <main className={styles.page}>
    <header className={styles.intro}><a className={styles.backLink} href="/ecosystem/">The open table</a><div className={styles.introGrid}><div><p className={styles.eyebrow}>YOUR WORKSPACE / ON THIS DEVICE</p><h1>A little intention.<br/><em>A useful next step.</em></h1></div><div className={styles.introNote}><p>Your plan is yours to use, edit or share. A small, completed contribution is a good beginning.</p><p className={styles.fine}>This workspace does not submit an application, create an account or join a mailing list.</p></div></div></header>
    <section className={styles.workspace} data-community data-home="../index.html" aria-label="Your local contribution plan">
      <div>
        <div data-empty-plan className={styles.empty}><span className={styles.eyebrow}>A FRESH PAGE</span><h2>Choose a path.<br/><em>Make it your own.</em></h2><p>No local plan is available in this browser. Create a first-step plan, or go straight to a free lesson or the community guide.</p><div className={styles.actions}><a className={styles.primary} href="/join/">Make my first-step plan</a><a className={styles.textLink} href="/sikh-bitcoin/">Start learning</a></div><p className={styles.fine}>If you already downloaded a plan, that file is yours to keep using. This page cannot read drafts from another browser or device.</p><a className={styles.textLink} href="/ecosystem/#ask-ma">Find a direction with Ma</a></div>
        <div data-plan-summary hidden className={styles.planSummary}>
          <div className={styles.planHeader}><p className={styles.eyebrow}>YOUR PERSONAL CONTRIBUTION PLAN</p><span className={styles.timeBadge} data-plan-time/><h2 data-plan-title/><p>A draft with a direction. You decide what happens next.</p></div>
          <ol className={styles.nextSteps}>
            <li><span className={styles.stepNumber}>01</span><div><p className={styles.eyebrow}>BEGIN WITH THE WORK</p><h3>Do one useful thing.</h3><p data-plan-task className={styles.taskText}/><a data-program-link href="/ecosystem/" className={styles.primary}>Open my program guide</a></div></li>
            <li><span className={styles.stepNumber}>02</span><div><p className={styles.eyebrow}>KEEP A COPY</p><h3>Take the plan with you.</h3><p data-plan-note className={styles.personalNote}/><div className={styles.actions}><button className={styles.primary} type="button" data-download>Download my plan</button><a href="/join/" className={styles.textLink}>Edit my plan</a></div><p className={styles.fine}>After downloading, open the Markdown file in a text editor or notes app. Add your work and source links as you go. Downloading does not send it to anyone.</p></div></li>
            <li><span className={styles.stepNumber}>03</span><div><p className={styles.eyebrow}>SHARE BY CHOICE</p><h3>Bring something back.</h3><p>When you have a question or a result to discuss, open a public GitHub draft. Review the text and remove private details before you submit. GitHub requires its own account to post.</p><a data-proposal-link href="https://github.com/Satnam-Satoshi/Satoshi-Langar/issues/new" className={styles.secondary}>Review a public proposal on GitHub</a><p className={styles.fine}>You can also keep working privately with your downloaded plan. There is no requirement to post.</p></div></li>
          </ol>
          <section className={styles.afterShare} aria-labelledby="after-share-title"><span className={styles.eyebrow}>AFTER YOU SUBMIT</span><h3 id="after-share-title">Keep the conversation in one place.</h3><p>Save your issue link and return to its discussion. Add source links, an example or a small result when it helps. A human reviewer may ask for a clearer scope before accepting work.</p><p className={styles.fine}>An assignment, payment or reply time is not guaranteed. An intake steward and response schedule are still being established.</p></section>
          <div className={styles.clearDraft}><button type="button" className={styles.textButton} data-clear>Remove my local contribution draft</button><p>Removes the saved draft from this browser. Downloads and anything you posted on GitHub remain separate.</p></div>
        </div>
        <p data-message role="status" aria-live="polite" className={styles.message}/>
      </div>
      <aside className={styles.aside}>
        <section className={styles.continueCard}><span className={styles.eyebrow}>YOUR NEXT OPEN DOOR</span><h2>Keep your<br/><em>curiosity moving.</em></h2><p>Your plan is one beginning. The rest of the table is open, too.</p><a href="/sikh-bitcoin/"><strong>Learn one thing</strong><span>63 free lessons and practical exercises</span></a><a href="/conversations/"><strong>Read the current LTC issue</strong><span>Original features and dated sources</span></a><a href="/miikey/"><strong>Understand your keys</strong><span>Wallets, recovery and custody education</span></a><a href="/ecosystem/#ask-ma"><strong>Ask the community guide</strong><span>Prepared answers and a useful next step</span></a></section>
        <section className={styles.accountCard}><span className={styles.status}>YOU CAN CONTINUE AS A GUEST</span><h3>No account needed.</h3><p>Google sign-in is available and optional. Your existing guest tools and public learning resources remain free to use.</p><a className={styles.textLink} href="/sign-in/">Check optional sign-in status</a><a className={styles.textLink} href="/join/#member-benefits">Explore community benefits</a></section>
        <p className={styles.asideNote}>Have a content correction? Keep the exact page and source date with your proposal. Never put personal records or wallet secrets in a public issue. <a href="/privacy/">Read our privacy and reporting limits.</a></p>
      </aside>
    </section>
    <footer className={styles.pageFooter}><p>Many ways to begin.<br/><strong>One open table.</strong></p><div><a href="/ecosystem/">Return to the community</a><a href="/conversations/archive/">Explore past issues</a><a href="/join/">Choose another path</a></div></footer>
  </main>;
}
