import { PageIntro } from '../components/PageIntro';
import { repo } from '../data/ecosystem';
export const metadata={title:'The roadmap'};
const phases=[
 ['01','Make the invitation useful','Days 1–14 after owners agree','Review the expanded site and three 21-lesson courses. Prepare official channels, contributor tasks and release continuity.','Gate A: a newcomer can find a useful action; mobile and sources pass review; a human intake owner and backup are named.'],
 ['02','Rehearse before operating','Days 15–30, subject to readiness','Plan a kitchen and meetup, rehearse service evidence and an artist invoice, and review three LTC editions.','Gate B: reviewers accept rehearsal evidence, including failures, disputes and privacy. Local events and payments need their own approval.'],
 ['03','Complete one accountable cycle','Days 31–60, subject to evidence','Run an approved local pilot, user-test the learning modules and complete a seven-day editorial rehearsal. Test payment and donation accounting before activation.','Gate C: a real approved cycle has a learning report. Daily publishing, checkout and donation intake each pass their own gate.'],
 ['04','Make it repeatable','Days 61–90, subject to evidence','Help a second operator reuse the playbook, test independent recovery and welcome a bounded external AI contribution.','Gate D: another human can repeat the process, restore the materials and stop agent access. Expand only where evidence supports it.'],
];
export default function Page(){return <main><PageIntro eyebrow="A practical path · October 1, 2026 · 0.1.26" title="Build trust at the speed of evidence." description="A 90-day direction for a community that can learn, create and serve. These are working phases, not promises of launch dates or financial returns."/><section className="reading-content wide-content">{phases.map(([n,title,time,body,gate])=><article className="roadmap-phase" key={n}><span className="inline-tag">PHASE {n} · {time}</span><h2>{title}</h2><p>{body}</p><p className="status-note">{gate}</p></article>)}<h2>What moves now</h2><p>Open learning materials, researched program designs, source collection, accessible pages and contributor tasks. Three focused agents supported the research, publication and roadmap work for this revision; ongoing jobs need named owners and explicit schedules.</p><h2>What needs a person</h2><ul><li>Account registration, recovery and moderation owners.</li><li>Donation accounting, beneficiary and custody arrangements; the published receiving addresses are already founder-supplied.</li><li>A city, willing kitchen host and food-safety lead.</li><li>An editor, education reviewer and first consenting artist.</li></ul><h2>What success means</h2><p>A newcomer understands custody. A guest is served with dignity. An artist gets the agreed payment. A reader can reproduce a number. An agent’s work stands up to review. Another human can restore the project without relying on one account.</p><a className="launch-button" href={`${repo}/blob/agent/community-ecosystem-20260930/ROADMAP.md`}>Read the detailed delivery plan ↗</a><p><a href={`${repo}/blob/agent/community-ecosystem-20260930/docs/ECOSYSTEM-PLAN.md`}>Program dependencies and acceptance criteria</a> · <a href="/join/">Find a first task</a></p></section></main>}
