import type { Metadata } from 'next';
import s from './mission.module.css';
export const metadata: Metadata = {
 title: 'Our mission · Make room for one more',
 description: 'A shared table, an open mind and something useful to give. Discover the human purpose behind Satnam Satoshi, LTC Media, Langar and Kalakar.x.',
 openGraph: { title: 'Make room for one more. · Satnam Satoshi', description: 'Open money. Shared knowledge. Service freely given.', images: [{url:'https://satnamsatoshi.com/images/mission/a-place-for-you.jpg',width:1536,height:1024,alt:'Original illustration of a community sharing food, knowledge and creative work.'}] },
 twitter: {card:'summary_large_image',title:'Make room for one more.',images:['https://satnamsatoshi.com/images/mission/a-place-for-you.jpg']}
};
const programs = [
 {n:'01',mark:'?',name:'Sikh Bitcoin',line:'Pass on an “aha.”',text:'Make a difficult idea feel possible. Learn with visual lessons and small experiments, then help someone else understand.',status:'Open learning',href:'/sikh-bitcoin/',action:'Find your first lesson'},
 {n:'02',mark:'∪',name:'Satoshi Langar',line:'Make a place at the table.',text:'Help design community kitchens around nourishment and dignity. People cook, welcome and care; tools help them plan.',status:'Pilot planning',href:'/langar/',action:'Explore the kitchen toolkit'},
 {n:'03',mark:'✳',name:'Kalakar.x',line:'Make something only you can.',text:'Help build a path for artists to keep their rights, receive bitcoin directly and choose how their work supports the commons.',status:'Creator pilot design',href:'/kalakar/',action:'Open the artist toolkit'},
 {n:'04',mark:'LTC',name:'Lunch Time Conversations',line:'Give curiosity good company.',text:'Read the daily magazine. Follow Bitcoin and Litecoin, inspect the evidence, and bring a better question to the conversation.',status:'Published editions',href:'/conversations/',action:'Read LTC Magazine'},
 {n:'05',mark:'↗',name:'MiiKey',line:'Turn independence into a skill.',text:'Understand keys, recovery and the responsibility behind self-custody. Start with knowledge, at your own pace.',status:'Open resource hub',href:'/miikey/',action:'Explore your next step'},
 {n:'06',mark:'+',name:'Agent Sangat',line:'Give intelligence a useful job.',text:'Contribute code, translations, research or accessible tools. Every agent gets a bounded task and an accountable human owner.',status:'Open contributions',href:'/agents/',action:'See how we build'}
];
function PrincipleArt({kind}:{kind:'share'|'learn'|'build'}) {return <svg viewBox="0 0 320 190" className={s.principleArt} aria-hidden="true">{kind==='share'?<><circle cx="160" cy="100" r="75" fill="#d7e2f1"/><ellipse cx="160" cy="105" rx="101" ry="35" fill="#b94624"/><path d="M78 109q82 76 164 0" fill="#e37a36"/><ellipse cx="160" cy="88" rx="49" ry="16" fill="#f9f1dd"/><path d="M143 62q-12-14 0-28m24 26q-12-14 0-28m24 32q-12-14 0-28" stroke="#233f70" strokeWidth="3" fill="none"/></>:kind==='learn'?<><circle cx="160" cy="94" r="74" fill="#f0c87b"/><path d="M58 66q52-29 102 0v104q-50-29-102 0z" fill="#f7f0de" stroke="#29497e" strokeWidth="2"/><path d="M262 66q-52-29-102 0v104q50-29 102 0z" fill="#d4e0f2" stroke="#29497e" strokeWidth="2"/><path d="M80 84l56 0m-56 21h56m-56 21h38m64-42h56m-56 21h56m-56 21h38" stroke="#29497e" strokeWidth="2"/><path d="M160 21v15m-25-7 9 12m41-12-9 12" stroke="#b94624" strokeWidth="3"/></>:<><path d="M63 129h194v33H63z" fill="#b94624"/><rect x="86" y="91" width="47" height="38" fill="#315b99"/><rect x="148" y="69" width="47" height="60" fill="#91b0d6"/><circle cx="211" cy="94" r="33" fill="#e9bb69"/><path d="M92 62h32m-16-16v32m99-36h22m-11-11v22" stroke="#233f70" strokeWidth="3"/><path d="m136 58 19-18 19 18" fill="none" stroke="#b94624" strokeWidth="3"/></>}</svg>}
export default function MissionPage(){return <main className={s.mission}>
 <div className={s.wrap}>
 <div className={s.overline}><span>Our story / Our reason to build</span><a href="/ecosystem/">Meet the open table ↗</a></div>
 <section className={s.hero} aria-labelledby="mission-title"><div><p className={s.eyebrow}>Satnam Satoshi · In service of humanity</p><h1 id="mission-title">Make room<br/>for <em>one more.</em></h1></div><div className={s.heroCopy}><p className={s.dek}>A meal. An idea. A little of your time.<br/>The world changes when we share them.</p><p>We bring people and responsibly guided AI together to learn, create and serve. Open technology is our tool. Human dignity is our reason.</p><a className={s.button} href="#your-place">There’s a place for you <span aria-hidden="true">↓</span></a></div></section>
 <figure className={s.heroArt}><img src="/images/mission/a-place-for-you.jpg" width="1536" height="1024" fetchPriority="high" alt="An imagined blue courtyard where people of different generations share a long orange table, food, an open book and creative work."/><figcaption><span>MANY HANDS. ONE HUMANITY.</span><small>Original illustration of the community we hope to build.</small></figcaption></figure>
 <nav className={s.chapterNav} aria-label="Our mission chapters"><a href="#why">01 / The spark</a><a href="#principles">02 / What matters</a><a href="#our-work">03 / The work</a><a href="#people">04 / People + AI</a><a href="#your-place">05 / Your place ↗</a></nav>
 <section id="why" className={s.spark}><div><p className={s.eyebrow}>01 / Begin with a human need</p><h2>What if our smartest tools<br/>helped us be<br/><em>better neighbours?</em></h2></div><div className={s.story}><p className={s.dropcap}>Someone needs a meal. Someone has a question they are afraid to ask. Someone has a gift to share and no obvious place to begin.</p><p>That is where our story starts. Before the code, the coin or the headline, there is a person.</p><p>Satnam Satoshi connects the curiosity of open-source technology with <strong>seva—service freely given.</strong> We want a useful lesson to become a shared skill, a creative idea to become honest work, and a community’s care to become something someone can feel.</p><p className={s.handwritten}>Pull up a chair. Bring your curiosity.</p></div></section>
 <section id="principles" className={s.section}><div className={s.sectionHead}><div><p className={s.eyebrow}>02 / The things we come back to</p><h2>Big ideas.<br/><em>Everyday practice.</em></h2></div><p>Guru Nanak’s wisdom of equality, honest work and sharing inspires our purpose. Everyone is welcome, whatever their faith or background.</p></div><div className={s.principles}><article><PrincipleArt kind="share"/><span className={s.eyebrow}>01 / Dignity</span><h3>Share the table.</h3><p>A person’s worth is not their wallet balance, technical knowledge or belief. Belonging begins with a welcome.</p></article><article><PrincipleArt kind="learn"/><span className={s.eyebrow}>02 / Curiosity</span><h3>Leave the door open.</h3><p>Explain the idea. Link the source. Make space for a newcomer’s question and an expert’s disagreement.</p></article><article><PrincipleArt kind="build"/><span className={s.eyebrow}>03 / Responsibility</span><h3>Make the work useful.</h3><p>Build openly, show what works, name what is unfinished, and be accountable to the people the work is meant to serve.</p></article></div></section>
 <section className={s.money} aria-labelledby="money-title"><div className={s.coinArt} aria-hidden="true"><span>₿</span><b>+</b><span>Ł</span><small>OPEN MONEY<br/>HUMAN PURPOSE</small></div><div><p className={s.eyebrow}>Bitcoin roots. Litecoin curiosity.</p><h2 id="money-title">Follow the rules.<br/><em>Keep asking why.</em></h2><p>Bitcoin gives us a monetary reference for long-term thinking: open rules, verifiable scarcity and individual sovereignty. Litecoin gives our community another rich story to explore, compare and understand.</p><p>Our Nakamoto standard is a commitment to learning about proof of work, peer-to-peer systems and the trade-offs behind them. You do not need to own a coin to take part.</p><div className={s.actions}><a href="/technology/">Explore our technology principles →</a><a href="/conversations/litecoin/">Follow the Litecoin story →</a></div><p className={s.note}>Independent community work. No Bitcoin or Litecoin institution’s endorsement is claimed.</p></div></section>
 <section id="our-work" className={s.section}><div className={s.sectionHead}><div><p className={s.eyebrow}>03 / One purpose, many ways to help</p><h2>Find your kind<br/>of <em>useful.</em></h2></div><p>The school, the kitchen, the studio and the newsroom belong in the same conversation. Here is how the work connects—and where it stands.</p></div><div className={s.programs}>{programs.map(p=><article key={p.n}><div className={s.cardTop}><span className={s.eyebrow}>{p.n} / {p.name}</span><span aria-hidden="true">{p.mark}</span></div><h3>{p.line}</h3><p>{p.text}</p><span className={s.status}>{p.status}</span><a href={p.href}>{p.action} <span aria-hidden="true">↗</span></a></article>)}</div><div className={s.thread}><span>Learn something.</span><b aria-hidden="true">→</b><span>Make it useful.</span><b aria-hidden="true">→</b><span>Share it openly.</span><b aria-hidden="true">→</b><span>Help someone begin.</span></div></section>
 <section id="people" className={s.people}><div><p className={s.eyebrow}>04 / People + AI, with purpose</p><h2>Many kinds of intelligence.<br/><em>A very human responsibility.</em></h2><p>AI Satoshi Ma helps us research, explain, design and build. Other agents can contribute too, with clear tasks and limits. People remain responsible for the mission, the decisions and the money.</p><a href="/agents/">Read how agents contribute →</a></div><div className={s.roles}><article><span>PEOPLE</span><h3>Set the purpose.<br/>Care for each other.</h3><p>Own decisions, review claims, govern resources and show up where human care matters.</p></article><article><span>AI & OPEN TOOLS</span><h3>Make useful work<br/>easier to do.</h3><p>Help with research, translation, accessible explanations, planning and code within explicit permissions.</p></article><p className={s.roleNote}>Our standard: clear permissions, visible evidence, a human owner and a way to stop.</p></div></section>
 <section id="your-place" className={s.section}><div className={s.sectionHead}><div><p className={s.eyebrow}>05 / Start small. Start somewhere.</p><h2>You don’t need<br/>to have <em>all the answers.</em></h2></div><p>Choose what feels like you. Each door leads to something you can explore right now, without a wallet or an account.</p></div><div className={s.doors}>{[{title:'“I’m just curious.”',text:'Start with a lesson or the latest magazine. Let one good question lead to the next.',href:'/sikh-bitcoin/',link:'Take a small first step'}, {title:'“I can make something.”',text:'Bring code, art, teaching, translation or an eye for detail. Build a practical contribution plan.',href:'/join/',link:'Find your contribution'}, {title:'“I want to help people.”',text:'Explore Langar, community projects and the work still needed to turn a purpose into a pilot.',href:'/ecosystem/',link:'Explore the open table'}].map(d=><article key={d.title}><h3>{d.title}</h3><p>{d.text}</p><a href={d.href}>{d.link} ↗</a></article>)}</div></section>
 <section className={s.promise}><span aria-hidden="true">✳</span><p className={s.eyebrow}>A promise worth working on</p><h2>Make knowledge open.<br/>Make technology useful.<br/><em>Make room for each other.</em></h2><p>This is an early, open-source effort. The learning and publishing spaces are open; community programs are still taking shape. The next chapter needs people willing to help build it.</p><div className={s.actions}><a className={s.button} href="/join/">Help write the next chapter ↗</a><a href="/roadmap/">See what comes next →</a></div></section>
 <aside className={s.sourceNote}><p><strong>Our inspirations, in their own words.</strong> Read <a href="https://bitcoin.org/bitcoin.pdf">Satoshi Nakamoto’s Bitcoin whitepaper ↗</a> and the <a href="https://www.sikhcoalition.org/blog/2019/national-partners-join-guru-nanak-550th-celebration/">Sikh Coalition’s Guru Nanak service initiative ↗</a>. This mission is our own application of those inspirations.</p><p><a href="/transparency/">How we stay accountable →</a> · <a href="https://github.com/Satnam-Satoshi/Satoshi-Langar">Explore the open-source project ↗</a></p></aside>
 </div></main>}
