import { SocialLinks } from '../components/SocialLinks';
import { ProjectQuickLinks } from '../components/ProjectQuickLinks';
import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import { latestLtcEdition, editionDateHref } from '../data/editions';
import './publication.css';
export const metadata: Metadata = {
 title: { default: 'LTC Magazine — Lunch Time Conversations', template: '%s · LTC Magazine' },
 icons: { icon: '/brand/ltc-media-mark.svg' },
 openGraph: { type: 'website', siteName: 'LTC Magazine', title: 'LTC Magazine — Lunch Time Conversations', description: 'Litecoin, Bitcoin and the people building open money. A Satnam Satoshi publication.' },
 twitter: { card: 'summary_large_image', title: 'LTC Magazine — Lunch Time Conversations', description: 'Litecoin, Bitcoin and the people building open money.' },
};
const latest = latestLtcEdition ? editionDateHref(latestLtcEdition.date) : '/conversations/archive/';
const links = [['Front page', '/conversations/'], ['Daily issue', latest], ['Litecoin', '/conversations/litecoin/'], ['Special edition', '/conversations/specials/proof-of-birthday/'], ['Community Wire', '/conversations/community/'], ['All desks', '/conversations/desks/'], ['Archive', '/conversations/archive/'], ['Donate BTC / LTC', '/donate/']];
export default function PublicationLayout({ children }: { children: ReactNode }) {
 return <div className="publication-shell" data-ltc-publication><header className="publication-header"><div className="publication-header-inner"><a className="publication-wordmark" href="/conversations/" aria-label="LTC Media front page"><img src="/brand/ltc-media-logo.svg" width="260" height="92" alt="LTC Media"/></a><nav className="publication-desktop-nav" aria-label="LTC main navigation">{links.map(([label,href])=><a href={href} key={label}>{label}</a>)}</nav><a className="publication-community" href="https://satnamsatoshi.com/">Satnam Satoshi ↗</a><details className="publication-menu"><summary>Menu <span aria-hidden="true">+</span></summary><nav aria-label="LTC mobile navigation">{links.map(([label,href])=><a href={href} key={label}>{label}</a>)}<a href="/sikh-bitcoin/">Learn Bitcoin</a><a href="/miikey/">MiiKey · Self-custody &amp; open tools</a><a href="/join/?path=ltc">Contribute to LTC</a><a href="/press/">Press &amp; share kit</a><a href="/connect/">Verified channels</a><a href="https://satnamsatoshi.com/">Satnam Satoshi community ↗</a></nav></details></div><ProjectQuickLinks/><SocialLinks/></header>{children}<footer className="publication-footer"><div className="publication-footer-top"><div><a href="/conversations/" className="publication-footer-brand"><img src="/brand/ltc-media-logo-light.svg" width="260" height="92" alt="LTC Media"/><span>Lunch Time Conversations</span></a><p>Open money. Open minds.<br/>A table for everyone.</p><SocialLinks mode="footer"/></div><nav aria-label="LTC footer navigation"><div><strong>Read</strong><a href={latest}>Latest daily issue</a><a href="/conversations/litecoin/">The Litecoin fieldbook</a><a href="/conversations/community/">Community Wire · Builders &amp; sources</a><a href="https://litecoinregister.com/?c=table">Litecoin Register ↗</a><a href="/conversations/specials/proof-of-birthday/">Proof of Birthday · Special edition</a><a href="/conversations/desks/">All 29 magazine sections</a><a href="/conversations/archive/">Every published issue</a><a href="/conversations/feed.xml">Follow by RSS ↗</a><a href="/sikh-bitcoin/">Learn Bitcoin</a><a href="/miikey/">MiiKey · Self-custody &amp; open tools</a></div><div><strong>Take part</strong><a href="/press/">Press &amp; share kit</a><a href="/connect/">Verified channels</a><a href="/langar/">Satoshi Langar · Food &amp; seva</a><a href="/kalakar/">Kalakar.x · Art &amp; Bitcoin</a><a href="/join/?path=ltc">Contribute to the magazine</a><a href="/conversations/about/">Editorial mission</a><a href="https://github.com/Satnam-Satoshi/Satoshi-Langar/issues/new?title=LTC%20source%20or%20correction">Submit a correction ↗</a><a href="/donate/">Donate BTC / LTC</a><a href="https://satnamsatoshi.com/">Satnam Satoshi community</a></div></nav></div><div className="publication-footer-bottom"><span>© 2026 LTC Media · A Satnam Satoshi project</span><a href="/privacy/">Privacy</a><span>AI-assisted. Human-governed. Open to questions.</span></div></footer></div>;
}
