import { LtcCurrentIssueBanner, LtcPublicationShelf } from '../components/LtcPublicationFlow';
import LtcNewsExtraCard from '../components/LtcNewsExtraCard';
import NewsroomUpdate from '../components/NewsroomUpdate';
import {newsroom} from '../data/newsroom';
import type { Metadata } from 'next';
import { NewsletterInvitation } from '../components/NewsletterInvitation';
import { magazineArticles, articleHref } from '../data/magazine';
import { latestLtcEdition, ltcPublicationDays, ltcPublicationMonths, editionDateHref, archiveMonthHref, formatEditionDate } from '../data/editions';
import { formatPublicationMonth } from '../data/edition-calendar';
import { LtcEditionCover } from '../components/LtcEditionPresentation';
import styles from './front-page.module.css';
export const metadata: Metadata = {
 title: 'LTC Media — The daily newsroom & magazine',
 description: 'Litecoin, Bitcoin and the world taking shape around them. Explore dated source briefings, illustrated daily issues, special editions and independent thinking.',
 alternates: { canonical: 'https://ltcmagazine.org/conversations/', types: { 'application/rss+xml': '/conversations/feed.xml' } },
 openGraph: { title: latestLtcEdition ? `LTC · ${latestLtcEdition.title}` : 'LTC Media — Lunch Time Conversations', description: 'The daily newsroom and magazine from Satnam Satoshi.', url: 'https://ltcmagazine.org/conversations/', images: [{url:`https://ltcmagazine.org/magazine/${latestLtcEdition?.presentation?.artDirection?.coverAsset ?? 'litecoin-open-network.jpg'}`,width:latestLtcEdition?.presentation?.artDirection?.coverAsset.startsWith('daily/')?1086:1536,height:latestLtcEdition?.presentation?.artDirection?.coverAsset.startsWith('daily/')?1448:1024}] }
};
function DeskArt({ kind }: { kind: 'clocks' | 'agents' | 'record' }) {
 return <svg className={styles.graphic} viewBox="0 0 480 320" role="img" aria-label={`${kind==='clocks'?'Three overlapping clock faces':kind==='agents'?'Open geometric forms joined by a shared thread':'Layered pages and a magnifying circle'}. Original editorial illustration, not a data chart.`}>{kind==='clocks'?<><circle cx="154" cy="146" r="90" fill="#283b32"/><circle cx="313" cy="146" r="90" fill="#c7592b"/><circle cx="235" cy="215" r="72" fill="#e2ba76" stroke="#25251f"/>{[[154,146],[313,146],[235,215]].map(([x,y],i)=><g key={x} stroke={i===0?'#f4ecdb':'#25251f'} strokeWidth="2" fill="none"><circle cx={x} cy={y} r={i===2?57:73}/><path d={`M${x} ${y-42}V${y}l${i===0?32:-30} ${i===1?-20:18}`}/><circle cx={x} cy={y} r="4"/></g>)}</>:kind==='agents'?<><path d="M50 228Q137 28 241 168T429 85" stroke="#b44723" strokeWidth="4" fill="none"/><rect x="70" y="83" width="90" height="136" rx="45" fill="#273a31"/><circle cx="246" cy="158" r="71" fill="#e1b269"/><path d="M321 72h90v181h-90z" fill="#bf5329"/><path d="M119 86v132M184 158h128M367 76v176" stroke="#f3eddf" strokeWidth="2" strokeDasharray="4 7"/><circle cx="246" cy="158" r="9" fill="#25251f"/></>:<>{[0,1,2,3].map(i=><g key={i} transform={`translate(${80+i*26},${58+i*14}) rotate(-8)`}><path d="M0 0h180v166H0z" fill={i===3?'#f4ecdb':'#cfb79a'} stroke="#25251f"/>{[30,54,78,102,126].map(y=><path key={y} d={`M20 ${y}h130`} stroke="#a69a83"/>)}</g>)}<circle cx="316" cy="181" r="70" stroke="#b44723" strokeWidth="17" fill="none"/><path d="M366 231l49 51" stroke="#b44723" strokeWidth="17"/></>}</svg>;
}
const comma=(value:string)=>{const [whole,fraction]=value.split('.');return whole.replace(/\B(?=(\d{3})+(?!\d))/g,',')+(fraction?`.${fraction}`:'')};
const special='/conversations/specials/proof-of-birthday/';
const desks=[
 {name:'Litecoin & its builders',detail:'Foundation · MWEB · mining · LitVM',href:'/conversations/litecoin/',mark:'Ł'},
 {name:'Policy & public records',detail:'SEC · CFTC · what the document says',href:'/conversations/desks/sec-cftc/',mark:'§'},
 {name:'Markets & institutions',detail:'Funds · holdings · the three clocks',href:'/conversations/desks/bitcoin-products/',mark:'↗'},
 {name:'Open financial systems',detail:'Morpho · cbBTC · cbLTC · risk',href:'/conversations/desks/morpho/',mark:'◎'},
 {name:'Money on new rails',detail:'Arc · USDC · EURC · dependencies',href:'/conversations/desks/circle-arc/',mark:'≋'},
 {name:'Sovereignty in practice',detail:'MiiKey · custody · people · tools',href:'/miikey/',mark:'⌘'}
];
export default function ConversationsPage(){
 const issue=latestLtcEdition, href=issue?editionDateHref(issue.date):'/conversations/archive/';
 const featured=['three-clocks-of-a-bitcoin-fund','give-the-agent-a-job','read-the-verb-before-the-headline'].map(slug=>magazineArticles.find(item=>item.slug===slug)!);
 const other=magazineArticles.filter(item=>!featured.includes(item));
 const quotes=newsroom.sources.filter(source=>source.id.startsWith('coinbase-')&&source.status==='collected'&&source.freshness==='dated-observation')??[];
 const agencyRecords=newsroom.policyRecords.sources.flatMap(feed=>feed.items.map(item=>({...item,agency:feed.title})))??[];
 const palette=issue?.presentation?.cover.palette??'cobalt';
 const layout=issue?.presentation?.artDirection?.layout??(['folio','atlas','dispatch'] as const)[Number(issue?.date.slice(-2)??0)%3];
 return <main className={styles.front} data-palette={palette} data-layout={layout} data-newsroom-date={issue?.date}>
 <div className={styles.dateline}><span>Independent thinking. Open money. Shared humanity.</span><span>{issue?`${formatEditionDate(issue.date)} / Latest published`:'The founding reading room'}</span></div>
 <header className={styles.nameplate}><div><span className={styles.wordmark}>LTC <small>MEDIA</small></span><h1>Lunch Time<br/><em>Conversations.</em></h1></div><p>A magazine.<br/>A newsroom.<br/><strong>A reason to stay curious.</strong></p></header>
 <nav className={styles.departments} aria-label="Magazine departments"><a href="#daily">The daily issue</a><a href="/subscribe/">Get the magazine</a><a href="#newsroom">The newsroom</a><a href="/conversations/community/">Community Wire</a><a href="/conversations/litecoin/">Litecoin</a><a href="https://litecoinregister.com/?c=table">Litecoin Register ↗</a><a href="#special-editions">Special editions</a><a href="#special">The birthday special</a><a href="#latest-update">Data update</a><a href="#ideas">Ideas</a><a href="#archive">Past issues</a><a href="/miikey/">MiiKey ↗</a></nav>
 <LtcCurrentIssueBanner/><section id="daily" className={styles.dailyHero} aria-labelledby="daily-title">
 <div className={styles.heroCopy}><p className={styles.eyebrow}>The daily / {issue?formatEditionDate(issue.date):'The archive'}</p><span className={styles.heroRubric}>THE FLAGSHIP DAILY.</span><h2 id="daily-title">{issue?.presentation?.artDirection?.version===2?<>Proof of<br/><em>Work.</em></>:issue?.title??'Keep the conversation.'}</h2><p className={styles.dek}>{issue?.presentation?.artDirection?.version===2?issue.title:<>Open money moves fast.<br/>Make a little room to understand it.</>}</p><p className={styles.description}>Our flagship daily brings Bitcoin and Litecoin into one conversation: the network pulse, dated Morpho markets, SEC and CFTC records, builders and the people making open money useful.</p><div className={styles.actions}><a className={styles.button} href={href}>Open the daily magazine <span aria-hidden="true">↗</span></a><a className={styles.textLink} href="#newsroom">Scan the newsroom ↓</a></div><div className={styles.editionFacts}><span><strong>{issue?.features?.stories.length??issue?.briefs.length??0}</strong>{issue?.features?'illustrated features':'source briefings'}</span><span><strong>{issue?.coverage?.pages.length??0}</strong>topic sections</span><a href={`${href}#sourcebook`}>Dates. Sources.<br/>On the record ↗</a></div><p className={styles.meta}>AI-prepared factual briefings · Exact source dates inside · A published edition, not a live newswire</p></div>
 {issue&&<div className={styles.jacketStage}><div className={styles.stageTop}><span>THE DAILY READING RITUAL</span><span>ISSUE / {issue.date.slice(5).replace('-','.')}</span></div><a className={styles.bookLink} href={href} aria-label={`Read the daily magazine for ${formatEditionDate(issue.date)}`}><LtcEditionCover edition={issue} mode="thumbnail"/></a><div className={styles.stageBottom}><span>Front cover → sourcebook → back page</span><a href={`${href}#edition-record`}>See what’s inside ↗</a></div></div>}
 </section>
 {quotes.length>0&&<section className={styles.marketStrip} aria-label="Dated market snapshots"><div className={styles.marketIntro}><p className={styles.eyebrow}>The market, sampled</p><h2>Two networks.<br/>One moment.</h2><p>Coinbase Exchange last trades from the dated newsroom update. One venue; not live quotes or a global index.</p></div>{quotes.map(source=><div className={styles.marketQuote} key={source.id}><span className={styles.marketSymbol} aria-hidden="true">{source.id==='coinbase-btc-usd'?'₿':'Ł'}</span><p className={styles.eyebrow}>{source.id==='coinbase-btc-usd'?'Bitcoin / USD':'Litecoin / USD'}</p><strong>${comma(source.observations![0].value)}</strong><time dateTime={source.sourceAsOf!}>{source.sourceAsOf} · UTC</time><a href="/conversations/updates/#sourcebook">Trace the observation ↗</a></div>)}</section>}
 <NewsroomUpdate/>
 <LtcNewsExtraCard/><div id="new-specials"><LtcPublicationShelf/></div>
 <section id="newsroom" aria-labelledby="newsroom-title"><div className={styles.sectionHead}><div><p className={styles.eyebrow}>On the record / Latest newsroom check</p><h2 id="newsroom-title">The newsroom.</h2></div><p>Prepared {newsroom.preparedAt}<br/>Every observation keeps its own date.</p></div><div className={styles.newsGrid}>{agencyRecords.map((record,index)=><article className={styles.newsCard} key={record.id}><div className={styles.newsTop}><span>{String(index+1).padStart(2,'0')}</span><p className={styles.eyebrow}>{record.agency}</p></div><h3><a href={record.url}>{record.title}</a></h3><p>Official agency release. Read the source document for its scope and legal status; this announcement keeps its original date.</p><div className={styles.newsBottom}><time dateTime={record.publishedAt}>Published: {record.publishedAt}</time><a href="/conversations/updates/#policy">Policy desk ↗</a></div></article>)}{newsroom.briefs.map((brief,index)=><article className={styles.newsCard} key={brief.id}><div className={styles.newsTop}><span>{String(index+1+agencyRecords.length).padStart(2,'0')}</span><p className={styles.eyebrow}>{brief.desk}</p></div><h3><a href="/conversations/updates/#sourcebook">{brief.headline}</a></h3><p>{brief.paragraphs[0]}</p><div className={styles.newsBottom}><time dateTime={brief.effectiveAt}>Source date: {brief.effectiveAt}</time><a href="/conversations/updates/#sourcebook" aria-label={`Read source briefing: ${brief.headline}`}>Read ↗</a></div></article>)}</div><details className={styles.coverageNote}><summary>How this newsroom updates—and what it does not cover yet</summary><p>The front page follows each successfully published daily edition, with an independently timestamped update notebook for checks between issues: its cover, palette, briefings, dated prices and archive links refresh together. Checks run on the daily publishing schedule; a failed or missed release leaves the last dated issue visible.</p><p>Our automated desk combines the original ten-source registry with separately validated network, Morpho and official agency-feed observations. Software releases keep their release dates; holdings records are not fund flows. Original features retain their research dates. Broader analysis, company and community reporting needs separately checked evidence. The topic guides below are background reading, not a claim that every desk has new reporting each day.</p><p><a href={`${href}#sourcebook`}>Inspect this issue’s sources and gaps →</a> · <a href="/conversations/about/">Editorial approach →</a></p></details></section>
 <NewsletterInvitation/>
 <section id="special" className={styles.special} aria-labelledby="special-title"><a className={styles.specialArt} href={special} aria-label="Open Proof of Birthday"><img src="/magazine/proof-of-birthday/cover.jpg" width="1024" height="1536" loading="lazy" alt="Silver candles spelling 15 above an open ledger: original Proof of Birthday cover art."/><span>15 YEARS.<br/>84 PAGES.<br/><em>ONE LONG STORY.</em></span></a><div className={styles.specialCopy}><p className={styles.eyebrow}>The collector’s read / Litecoin at fifteen</p><h2 id="special-title"><a href={special}>Proof of<br/><em>Birthday.</em></a></h2><p className={styles.specialDek}>Maturing beautifully.<br/>Still making blocks.</p><p>From Charlie Lee’s first announcement to mining families, MWEB, the Foundation and the institutional record. An illustrated journey through the people and ideas behind Litecoin.</p><a className={styles.lightButton} href={special}>Explore the 84-page special ↗</a><a className={styles.textLink} href={`${special}#contents`}>Browse the illustrated index →</a><p className={styles.specialMeta}>Founder reviewed October 4, 2026 · Advance edition<br/>Research through October 4 · Planned cover October 15</p></div></section>
 <section className={styles.fieldbook} aria-labelledby="fieldbook-title"><div><p className={styles.eyebrow}>The Litecoin fieldbook / Keep exploring</p><h2 id="fieldbook-title">Follow the<br/><em>silver thread.</em></h2><p>Meet the builders. Understand MWEB. Explore Foundation projects, payments, mining and LitVM—with working systems and proposals clearly distinguished.</p><a className={styles.textLink} href="/conversations/litecoin/">Enter the world of Litecoin ↗</a></div><a href="/conversations/litecoin/" aria-label="Explore the Litecoin fieldbook"><img src="/magazine/litecoin-open-network.jpg" width="1536" height="1024" loading="lazy" alt="Conceptual silver and blue open-network illustration for the Litecoin fieldbook."/></a></section>
 <section aria-labelledby="desks-title"><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Choose your next question</p><h2 id="desks-title">Across the desks.</h2></div><a className={styles.textLink} href="/conversations/desks/">All 29 magazine sections ↗</a></div><nav className={styles.deskGrid} aria-label="Topic reading desks">{desks.map(desk=><a href={desk.href} key={desk.name}><span aria-hidden="true">{desk.mark}</span><h3>{desk.name}</h3><p>{desk.detail}</p><small>Explore the guide ↗</small></a>)}</nav></section>
 <aside className={styles.register}><span aria-hidden="true">Ł</span><div><p className={styles.eyebrow}>Research beyond our newsroom</p><h2>Open the Litecoin Register.</h2><p>Explore an independent third-party Litecoin tracker. Check each entry’s source, definition and date before comparing figures; tracker holdings are not fund flows.</p><a className={styles.textLink} href="https://litecoinregister.com/?c=table">Visit Litecoin Register ↗</a></div><small>EXTERNAL RESOURCE<br/>No affiliation claimed</small></aside>
 <section id="ideas" aria-labelledby="ideas-title"><div className={styles.sectionHead}><div><p className={styles.eyebrow}>The weekend mind, any day of the week</p><h2 id="ideas-title">Go a little deeper.</h2></div><p>Original explainers &amp; ideas.<br/>Read slowly. Bring questions.</p></div><div className={styles.featureGrid}>{featured.map((story,index)=><article className={styles.featureCard} key={story.slug}><a href={articleHref(story.slug)} aria-label={`Read ${story.title}`}><DeskArt kind={(['clocks','agents','record'] as const)[index]}/></a><p className={styles.eyebrow}>{story.desk}</p><h3><a href={articleHref(story.slug)}>{story.title}</a></h3><p>{story.dek}</p><a className={styles.textLink} href={articleHref(story.slug)}>{story.minutes} min · Editorial preview ↗</a></article>)}</div><p className={styles.editorialNote}>Original AI-prepared editorial previews await independent human review. These essays are separate from the dated daily source briefings.</p></section>
 <section className={styles.miikey} aria-labelledby="miikey-title"><a href="/miikey/" aria-label="Explore MiiKey"><img src="/miikey/keys-to-open-world.jpg" width="1536" height="1024" loading="lazy" alt="Original illustration of a silver key opening a doorway toward a connected community."/></a><div><p className={styles.eyebrow}>Meet MiiKey / An open door to self-custody</p><h2 id="miikey-title">Your keys.<br/><em>Your next chapter.</em></h2><p>Understand the responsibility behind “not your keys, not your coins.” Explore recovery, hardware wallets, multisig and tools for a more independent digital life.</p><a className={styles.lightButton} href="/miikey/">Open the MiiKey resource hub ↗</a><p className={styles.small}>Learn freely. No wallet connection required.</p></div></section>
 <section id="archive" aria-labelledby="archive-title"><div className={styles.sectionHead}><div><p className={styles.eyebrow}>The issue library / Every published day has a home</p><h2 id="archive-title">Keep a little history.</h2></div><a className={styles.textLink} href="/conversations/archive/">Every issue + special edition ↗</a></div><div className={styles.archiveGrid}>{ltcPublicationDays.slice(0,3).map(day=><article key={day.date}><a className={styles.archiveCover} href={editionDateHref(day.date)} aria-label={`Read ${formatEditionDate(day.date)}`}><LtcEditionCover edition={day.latest} mode="thumbnail"/></a><time dateTime={day.date}>{formatEditionDate(day.date)}</time><h3><a href={editionDateHref(day.date)}>{day.latest.title}</a></h3><a className={styles.textLink} href={editionDateHref(day.date)}>Return to this day ↗</a></article>)}</div><nav className={styles.calendarLinks} aria-label="Publication calendars">{ltcPublicationMonths.slice(0,3).map(month=><a key={month.month} href={archiveMonthHref(month.month)}>{formatPublicationMonth(month.month)} <span>{month.days.length} published {month.days.length===1?'day':'days'} ↗</span></a>)}</nav></section>
 <section id="reading-room" aria-labelledby="world-title"><div className={styles.sectionHead}><div><p className={styles.eyebrow}>More from the reading room</p><h2 id="world-title">The world around the block.</h2></div><a className={styles.textLink} href="/conversations/events/">The global events desk ↗</a></div><div className={styles.readingRows}>{other.map((story,index)=><article key={story.slug}><span>{String(index+1).padStart(2,'0')}</span><div><p className={styles.eyebrow}>{story.desk}</p><h3><a href={articleHref(story.slug)}>{story.title}</a></h3><p>{story.dek}</p><a className={styles.textLink} href={articleHref(story.slug)}>{story.minutes} min · Editorial preview ↗</a></div></article>)}</div></section>
 <aside className={styles.invitation}><span aria-hidden="true">✳</span><div><p className={styles.eyebrow}>The conversation belongs to all of us</p><h2>Bring a better question.</h2><p>First-time reader, lifelong Bitcoiner, Litecoin builder or open-source contributor. There is a place for your curiosity at this table.</p><div className={styles.actions}><a className={styles.button} href="/join/?path=ltc">Contribute to LTC ↗</a><a className={styles.textLink} href="/conversations/feed.xml">Follow each new issue by RSS ↗</a></div></div></aside>
 </main>;
}
