import type { Metadata } from 'next';
import { magazineArticles, articleHref } from '../data/magazine';
import { latestLtcEdition, ltcPublicationMonths, editionDateHref, archiveMonthHref, formatEditionDate } from '../data/editions';
import { formatPublicationMonth } from '../data/edition-calendar';
import { LtcEditionCover } from '../components/LtcEditionPresentation';
import styles from './front-page.module.css';
export const metadata: Metadata = { title: 'LTC Media · Lunch Time Conversations', description: 'A daily magazine for curious Bitcoiners. Read the latest issue, explore original essays and keep a record of the evidence.', alternates: { types: { 'application/rss+xml': '/conversations/feed.xml' } } };
function DeskArt({ kind }: { kind: 'clocks' | 'agents' | 'record' }) {
 return <svg className={styles.graphic} viewBox="0 0 480 320" role="img" aria-label={`${kind==='clocks'?'Three overlapping clock faces':kind==='agents'?'Open geometric forms joined by a shared thread':'Layered pages and a magnifying circle'}. Original editorial illustration, not a data chart.`}>{kind==='clocks'?<><circle cx="154" cy="146" r="90" fill="#283b32"/><circle cx="313" cy="146" r="90" fill="#c7592b"/><circle cx="235" cy="215" r="72" fill="#e2ba76" stroke="#25251f"/>{[[154,146],[313,146],[235,215]].map(([x,y],i)=><g key={x} stroke={i===0?'#f4ecdb':'#25251f'} strokeWidth="2" fill="none"><circle cx={x} cy={y} r={i===2?57:73}/><path d={`M${x} ${y-42}V${y}l${i===0?32:-30} ${i===1?-20:18}`}/><circle cx={x} cy={y} r="4"/></g>)}</>:kind==='agents'?<><path d="M50 228Q137 28 241 168T429 85" stroke="#b44723" strokeWidth="4" fill="none"/><rect x="70" y="83" width="90" height="136" rx="45" fill="#273a31"/><circle cx="246" cy="158" r="71" fill="#e1b269"/><path d="M321 72h90v181h-90z" fill="#bf5329"/><path d="M119 86v132M184 158h128M367 76v176" stroke="#f3eddf" strokeWidth="2" strokeDasharray="4 7"/><circle cx="246" cy="158" r="9" fill="#25251f"/></>:<>{[0,1,2,3].map(i=><g key={i} transform={`translate(${80+i*26},${58+i*14}) rotate(-8)`}><path d="M0 0h180v166H0z" fill={i===3?'#f4ecdb':'#cfb79a'} stroke="#25251f"/>{[30,54,78,102,126].map(y=><path key={y} d={`M20 ${y}h130`} stroke="#a69a83"/>)}</g>)}<circle cx="316" cy="181" r="70" stroke="#b44723" strokeWidth="17" fill="none"/><path d="M366 231l49 51" stroke="#b44723" strokeWidth="17"/></>}</svg>;
}
const comma=(value:string)=>{const [whole,fraction]=value.split('.');return whole.replace(/\B(?=(\d{3})+(?!\d))/g,',')+(fraction?`.${fraction}`:'')};
export default function ConversationsPage(){
 const issue=latestLtcEdition, href=issue?editionDateHref(issue.date):'/conversations/archive/';
 const lead=magazineArticles[0];
 const featured=['three-clocks-of-a-bitcoin-fund','give-the-agent-a-job','read-the-verb-before-the-headline'].map(slug=>magazineArticles.find(item=>item.slug===slug)!);
 const other=magazineArticles.filter(item=>item!==lead&&!featured.includes(item));
 const quotes=issue?.sources.filter(source=>source.id.startsWith('coinbase-')&&source.status==='collected'&&source.freshness==='dated-observation')??[];
 return <main className={styles.front}>
 <div className={styles.dateline}><span>Bitcoin · Culture · Open technology</span><span>{issue?`${formatEditionDate(issue.date)} / Latest published`:'The founding reading room'}</span></div>
 <header className={styles.nameplate}><h1><span>Lunch Time</span><em>Conversations.</em></h1><p>A daily reading ritual.<br/>An open invitation<br/>to think for yourself.</p></header>
 <nav className={styles.departments} aria-label="Magazine departments"><a href="#daily">The daily</a><a href="#ideas">Ideas & institutions</a><a href="#reading-room">Bitcoin & the world</a><a href="/conversations/events/">Global events</a><a href="/conversations/archive/">Past issues ↗</a></nav>
 <section className={styles.hero} aria-label="Front-page stories"><article className={styles.lead}><a href={articleHref(lead.slug)} aria-label={`Read ${lead.title}`}><figure><img src="/magazine/open-table-editorial.jpg" alt="An illustrated open book unfolds into a communal table beneath ink arches and an orange sun." width="1536" height="1024" fetchPriority="high"/><figcaption>Imagining the open table · Original AI-generated editorial artwork</figcaption></figure></a><p className={styles.eyebrow}>The opening conversation / Bitcoin & proof of work</p><h2><a href={articleHref(lead.slug)}>{lead.title}</a></h2><p className={styles.description}>{lead.dek}</p><p className={styles.meta}>Original explainer · {lead.minutes} min read · AI-prepared editorial preview</p><a className={styles.readLink} href={articleHref(lead.slug)}>Read the opening story <span aria-hidden="true">↗</span></a></article>
 <aside className={styles.issueDesk} aria-labelledby="latest-issue"><div className={styles.issueDeskHeader}><h2 id="latest-issue">The daily issue</h2><span>READ · KEEP · RETURN</span></div>{issue&&<><a className={styles.bookLink} href={href} aria-label={`Read the daily magazine for ${formatEditionDate(issue.date)}`}><LtcEditionCover edition={issue} mode="thumbnail"/></a><p className={styles.eyebrow}>{formatEditionDate(issue.date)} · Saved edition</p><h3>{issue.title}</h3><p>{issue.briefs.length} source briefings. A front cover, a reading sequence and a question for the way home.</p><a className={styles.button} href={href}>Open the magazine <span aria-hidden="true">↗</span></a><p className={styles.meta}>AI-prepared. Source dates and coverage notes travel with every issue.</p></>}<div className={styles.issueLinks}><a href="/conversations/archive/">Browse past issues →</a><a href="/conversations/feed.xml">Follow by RSS ↗</a></div></aside></section>
 <section id="daily" aria-labelledby="daily-title"><div className={styles.sectionHead}><h2 id="daily-title">In the daily.</h2><a href={href}>Read the complete issue ↗</a></div><div className={styles.briefGrid}>{issue?.briefs.slice(0,3).map((brief,index)=><article key={brief.id} className={styles.brief}><span>{String(index+1).padStart(2,'0')}</span><p className={styles.eyebrow}>{brief.desk}</p><h3><a href={`${href}#${brief.id}`}>{brief.headline}</a></h3><p>{brief.paragraphs[0]}</p><time dateTime={brief.effectiveAt}>Source date: {brief.effectiveAt}</time></article>)}</div></section>
 {quotes.length>0&&<section className={styles.marketStrip} aria-label="Dated market snapshots"><div><h3>A moment in<br/>the market.</h3><p>Coinbase Exchange last trades, sampled for this issue. Not live quotes or a global price index.</p><a href={`${href}#sourcebook`}>Check the sourcebook →</a></div>{quotes.map(source=><div key={source.id}><p className={styles.eyebrow}>{source.id==='coinbase-btc-usd'?'BITCOIN / USD':'LITECOIN / USD'}</p><strong className={styles.marketValue}>${comma(source.observations![0].value)}</strong><p><time dateTime={source.sourceAsOf!}>{source.sourceAsOf} · UTC</time></p></div>)}</section>}
 <section id="ideas" aria-labelledby="ideas-title"><div className={styles.sectionHead}><h2 id="ideas-title">A little further down<br/>the rabbit hole.</h2><p>Original explainers & field guides</p></div><div className={styles.featureGrid}>{featured.map((story,index)=><article className={styles.featureCard} key={story.slug}><a href={articleHref(story.slug)} aria-label={`Read ${story.title}`}><DeskArt kind={(['clocks','agents','record'] as const)[index]}/></a><p className={styles.eyebrow}>{story.desk}</p><h3><a href={articleHref(story.slug)}>{story.title}</a></h3><p>{story.dek}</p><a className={styles.readLink} href={articleHref(story.slug)}>{story.classification} · {story.minutes} min <span aria-hidden="true">↗</span></a></article>)}</div><p className={styles.editorialNote}>The reading room contains original AI-prepared editorial previews. Independent human review is pending. These explainers and analysis are separate from the dated daily source briefings.</p></section>
 <aside className={styles.quoteBand} aria-label="The LTC editorial spirit"><span aria-hidden="true">✳</span><div><h2>Conviction is welcome.<br/>So is a better question.</h2><p>Our Nakamoto standard: inspect the rules, follow the evidence and keep the door open for the next person. <a href="/technology/">Explore our principles →</a></p></div></aside>
 <section id="reading-room" aria-labelledby="world-title"><div className={styles.sectionHead}><h2 id="world-title">Bitcoin. And the world around it.</h2><a href="/conversations/archive/">The full reading room ↗</a></div><div className={styles.readingRows}>{other.map((story,index)=><article className={styles.readingRow} key={story.slug}><span>{String(index+1).padStart(2,'0')}</span><div><p className={styles.eyebrow}>{story.desk}</p><h3><a href={articleHref(story.slug)}>{story.title}</a></h3><p>{story.dek}</p><a className={styles.readLink} href={articleHref(story.slug)}>{story.minutes} min · Editorial preview ↗</a></div></article>)}</div></section>
 <section className={styles.paths} aria-label="Choose a reading path"><article><p className={styles.eyebrow}>Your first Bitcoin conversation</p><h2>Start with curiosity.<br/>No coins required.</h2><p>A plain-language path through money, keys and verification. Read freely, and learn one useful idea at a time.</p><a href="/sikh-bitcoin/course/foundations/">Begin the 21-lesson foundation course →</a></article><article><p className={styles.eyebrow}>Already down the rabbit hole?</p><h2>Keep your edge.<br/>Keep checking.</h2><p>Protocol depth, custody, Lightning and institutions. Bring your experience—and help make someone’s first step easier.</p><a href="/sikh-bitcoin/course/deep-dive/">Explore Bitcoin Deep Dive →</a></article></section>
 <section className={styles.archiveBand} aria-labelledby="archive-title"><div><p className={styles.eyebrow}>A daily publication. A growing collection.</p><h2 id="archive-title">Yesterday is<br/>still worth reading.</h2><p>Every published day has a permanent home. Return to its cover, stories, sourcebook and closing page, with corrections preserved.</p><a className={styles.readLink} href="/conversations/archive/">Enter the issue library ↗</a></div><nav aria-label="Publication calendar">{ltcPublicationMonths.slice(0,3).map(month=><a key={month.month} href={archiveMonthHref(month.month)}>{formatPublicationMonth(month.month)}<span>{month.days.length} published {month.days.length===1?'day':'days'} ↗</span></a>)}<a href="/conversations/feed.xml">Receive the next issue<span>RSS feed ↗</span></a></nav></section>
 </main>;
}
