import type { Metadata } from 'next';
import { litecoinEditorialMeta as meta, litecoinSources, litecoinStories, litecoinSystemLayers, litecoinLitvmRoadmap, litecoinProjects, litecoinSocialChannels, litecoinSocialPosts, litecoinParticipation } from '../../data/litecoin-editorial';
import LtcStoryArt from '../../components/LtcStoryArt';
import LtcVisualExplainer from '../../components/LtcVisualExplainer';
import styles from './litecoin.module.css';
export const metadata:Metadata={title:'The Litecoin fieldbook · LTC Media',description:'An illustrated independent guide to the Litecoin Foundation, MWEB, Nexus, LitVM and the people building useful open tools.'};
const sourceById=new Map(litecoinSources.map(s=>[s.id,s]));
const date=(value:string)=>new Intl.DateTimeFormat('en-US',{dateStyle:'long',timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`));
function Citations({ids}:{ids:string[]}) {return <p className={styles.sources}>{ids.map(id=>{const s=sourceById.get(id)!;return <a key={id} href={s.url}>{s.title} ↗</a>;})}</p>}
export default function LitecoinFieldbook(){return <main className={styles.page}>
 <div className={styles.topline}><a href="/conversations/">LTC / Lunch Time Conversations</a><span>Independent fieldbook · Checked {date(meta.checkedAt)}</span></div>
 <header className={styles.cover}><div className={styles.coverCopy}><p className={styles.kicker}>The open-money series / No. 01</p><h1>Litecoin.<br/><em>Beyond<br/>the ticker.</em></h1><p className={styles.dek}>Money, privacy and the people building the next useful thing.</p><a href="#fieldbook-contents" className={styles.cta}>Step inside the fieldbook <span>↓</span></a></div><div className={styles.coverArt}><LtcStoryArt priority caption={false}/><div className={styles.coverSeal}><span>CODE<br/>CULTURE<br/>CONTRIBUTION</span><strong>Ł</strong></div></div><footer><span>BITCOIN ROOTS. LITECOIN CURIOSITY.</span><span>Original AI-generated conceptual artwork</span></footer></header>
 <section className={styles.editorsLetter}><p className={styles.kicker}>A note from the editorial desk</p><div><h2>A network is more<br/>than its price.</h2><p>There are people writing code, testing wallets, explaining privacy and asking what money should make possible. This is a place to understand their work—and to ask better questions about it.</p><p className={styles.note}>{meta.independence} {meta.classification}. {meta.method}</p></div></section>
 <nav className={styles.contents} id="fieldbook-contents" aria-label="Litecoin fieldbook contents">{[['01','The Foundation','foundation'],['02','MWEB & its boundaries','mweb'],['03','The security record','mweb-security'],['04','LitVM, explained','litvm'],['05','Privacy roadmap','litvm-privacy'],['06','Nexus & everyday use','nexus'],['07','Project directory','projects'],['08','From official channels','social']].map(([n,title,id])=><a href={`#${id}`} key={id}><span>{n}</span>{title}<i aria-hidden="true">↗</i></a>)}</nav>
 <section className={styles.layers} aria-labelledby="layers-title"><div className={styles.sectionLabel}><span>THE SYSTEM MAP</span><span>Three identities. Three sets of questions.</span></div><h2 id="layers-title">Know which layer<br/><em>you’re talking about.</em></h2><div className={styles.layerGrid}>{litecoinSystemLayers.map((layer,i)=><article key={layer.id}><span className={styles.layerNumber}>{String(i+1).padStart(2,'0')}</span><p className={styles.kicker}>{layer.role}</p><h3>{layer.label}</h3><p>{layer.detail}</p><strong>{layer.stage}</strong></article>)}</div></section>
 {litecoinStories.map((story,i)=><article key={story.id} id={story.id} className={styles.story} data-style={i%3}><header className={styles.storyHeading}><span className={styles.bigNumber}>{String(i+1).padStart(2,'0')}</span><div><p className={styles.kicker}>{story.kicker}</p><h2>{story.title}</h2><p className={styles.dek}>{story.dek}</p><p className={styles.recordDate}>{story.status}{story.eventDate&&<> · Source date: <time dateTime={story.eventDate}>{date(story.eventDate)}</time></>}</p></div></header>
   {i===0||i===1||i===3?<div className={styles.storyVisual}><LtcStoryArt kind={i===1?'privacy':i===3?'builders':'network'}/></div>:null}
   <div className={styles.storyColumns}><div className={styles.prose}>{story.paragraphs.map(p=><p key={p}>{p}</p>)}<Citations ids={story.sourceIds}/></div><aside className={styles.marginNote}><span>THE USEFUL QUESTION</span><p>{story.takeaway}</p><a href={i===3?'/conversations/desks/builders/':i===1||i===2?'/conversations/desks/mweb/':'/conversations/desks/litecoin-foundation/'}>Keep reading in the desk guide ↗</a></aside></div>
   {i===1&&<LtcVisualExplainer deskId="mweb"/>}
   {i===3&&<div className={styles.roadmap}><p className={styles.kicker}>The project’s proposed sequence / not a completion tracker</p><ol>{litecoinLitvmRoadmap.map(step=><li key={step.step}><span>{step.step}</span><div><h3>{step.label}</h3><p>{step.detail}</p></div></li>)}</ol><p className={styles.note}>Read the current architecture documents for changes. LiteForge testnet access does not establish production readiness, bridge safety or present Litecoin settlement.</p></div>}
   <footer className={styles.folio}><span>LTC / THE LITECOIN FIELDBOOK</span><a href="#fieldbook-contents">Contents ↑</a><span>{String(i+1).padStart(2,'0')}</span></footer>
 </article>)}
 <section className={styles.projects} id="projects"><div className={styles.sectionLabel}><span>THE PROJECT DIRECTORY</span><a href={meta.directoryUrl}>Foundation’s full directory ↗</a></div><h2>Many hands.<br/><em>Useful work.</em></h2><p className={styles.sectionDek}>A selected map of Foundation initiatives and ecosystem projects. Read each stage before treating a prototype, funding campaign or directory listing as finished software.</p><div className={styles.projectGrid}>{litecoinProjects.map((p,i)=><article key={p.id}><div className={styles.projectTop}><span>{p.category}</span><span>{String(i+1).padStart(2,'0')}</span></div><h3><a href={p.sourceUrl}>{p.name} ↗</a></h3><p>{p.summary}</p><strong className={styles.stage}>{p.status}</strong><details><summary>Relationship & evidence</summary><p>{p.relationship}. {p.limitation}</p><p>Source {p.sourceDate?`dated ${date(p.sourceDate)}`:'does not display a publication date'}; checked {date(p.checkedAt)}.</p></details></article>)}</div></section>
 <section className={styles.social} id="social"><div className={styles.sectionLabel}><span>FROM OFFICIAL CHANNELS</span><span>Attribution before amplification</span></div><h2>Follow the people.<br/><em>Keep the source.</em></h2><div className={styles.channelGrid}>{litecoinSocialChannels.map(channel=><article key={channel.id}><span className={styles.socialMark} aria-hidden="true">↗</span><p className={styles.kicker}>Official X account</p><h3>{channel.name}</h3><a className={styles.handle} href={channel.url}>{channel.handle} ↗</a><p>{channel.note}</p><a href={channel.verifiedByUrl} className={styles.verify}>Check the official account link →</a></article>)}</div>{litecoinSocialPosts.map(post=><article className={styles.post} key={post.id}><div><p className={styles.kicker}>{post.title}</p><h3>{post.account}</h3><time dateTime={post.publishedAt}>{date(post.publishedAt)}</time></div><div><p>{post.summary}</p><a href={post.url}>Read the original X post ↗</a><small>{post.status}. {post.note}</small></div></article>)}<p className={styles.note}>These are links to official channels and one historical post. A current social timeline was not available for verification. No X tracking script loads on this page, and this is not a live social feed.</p></section>
 <section className={styles.sourcebook} id="sources"><h2>The fieldbook’s source shelf.</h2><p>Follow the announcement date, not just the day we checked it.</p><details><summary>Inspect {litecoinSources.length} source records <span>+</span></summary><ol>{litecoinSources.map(s=><li key={s.id}><a href={s.url}>{s.title} ↗</a><p>{s.publisher} · {s.classification} · {s.publishedAt?`Published ${date(s.publishedAt)}`:'Publication date not supplied'} · Checked {date(s.checkedAt)}</p><p>{s.note}</p></li>)}</ol></details></section>
 <section className={styles.closing}><p className={styles.kicker}>The next page is a contribution</p><h2>Bring your curiosity.<br/><em>Leave something useful.</em></h2><div>{litecoinParticipation.map(item=><a href={item.href} key={item.title}><strong>{item.title} ↗</strong><span>{item.detail}</span></a>)}</div><p>Read freely. No purchase, wallet or account is needed to explore.</p></section>
 </main>}
