import type { Metadata } from 'next';
import styles from './daily.module.css';

export const metadata: Metadata = { title: 'LTC Daily · 2 October 2026', description: 'Lunch Time Conversations, the Satnam Satoshi Bitcoin, Litecoin and Nakamoto Standard daily magazine.' };
const pdf = 'https://drive.google.com/file/d/1HCo-XodKJBzZ_ARQMVze0xzNyNqSAfP0/view?usp=drivesdk';
const btcCompanies = [['Strategy','847,666'],['Twenty One','43,514'],['Metaplanet','43,000'],['MARA','35,577'],['Strive','27,462'],['Bullish','22,000'],['Coinbase','17,311'],['CleanSpark','13,703'],['Trump Media','12,062'],['Tesla','11,509'],['Riot','11,380'],['Hut 8','10,278'],['Block','9,117'],['American Bitcoin','8,300'],['GD Culture','7,500'],['Galaxy','6,894'],['Next Technology','5,833'],['Gemini','5,528'],['Silvia','5,130'],['Boyaa','4,468'],['Nakamoto Inc','4,467']];
const products = [['IBIT','800,535'],['Fidelity Wise Origin','184,058'],['GBTC','131,528'],['Grayscale Mini','62,874'],['Bitwise Bitcoin','38,189'],['ARK 21Shares','35,026'],['CoinShares Physical','21,270'],['CoinShares Tracker One','20,850'],['WisdomTree Physical','19,260'],['Purpose Bitcoin','18,373'],['iShares Bitcoin ETP','18,002'],['Fidelity Advantage','14,898'],['VanEck Trust','14,767'],['Bitwise Physical ETC','10,771'],['Morgan Stanley','10,436'],['21Shares Bitcoin ETP','8,195'],['VanEck Bitcoin ETN','8,195'],['CI Galaxy','8,016'],['CoinShares Valkyrie','6,410'],['Franklin Bitcoin','6,331'],['Invesco Physical ETN','4,402']];
const source = {btc:'https://bitcointreasuries.net/',products:'https://bitcointreasuries.net/etfs-and-exchanges',ltc:'https://litecoinregister.com/',circle:'https://www.circle.com/blog',morphoLtc:'https://app.morpho.org/base/variable/0x9125d0fa03c3137166df68bcc72283477830de2a4a5536512374c573ad4583c3/usdc-cbltc',morphoBtc:'https://app.morpho.org/base/variable/0x9103c3b4e834476c9a62ea009ba2c884ee42e94e6e314a26f04d312434191836/usdc-cbbtc'};
function Ranking({title,rows,unit,href}:{title:string;rows:string[][];unit:string;href:string}) {return <section className={styles.ranking}><div className={styles.sectionTitle}><h2>{title}</h2><a href={href}>Source ↗</a></div><div className={styles.tableWrap}><table><caption>Tracker-reported holdings, October 2 snapshot; product structures and issuer dates vary.</caption><thead><tr><th scope="col">#</th><th scope="col">Name</th><th scope="col">{unit}</th></tr></thead><tbody>{rows.map(([name,value],i)=><tr key={name}><td>{String(i+1).padStart(2,'0')}</td><th scope="row">{name}</th><td>{value}</td></tr>)}</tbody></table></div></section>}
export default function DailyEdition(){return <main className={styles.paper}>
  <div className={styles.top}><span>Satnam Satoshi Project</span><span>Issue 01 / 02 October 2026</span></div>
  <header className={styles.cover}><p className={styles.eyebrow}>LTC / Lunch Time Conversations</p><h1>The proof<br/>of work<br/><em>issue.</em></h1><div className={styles.orbit} aria-hidden="true"><span>₿</span><span>Ł</span></div><p className={styles.deck}>Capital. Code. Custody.<br/>Bitcoin · Litecoin · The Nakamoto Standard.</p><a className={styles.button} href={pdf}>Read the 29-page magazine ↗</a><p className={styles.coverFoot}>Original daily editorial · Source trail inside · PDF on Google Drive</p></header>
  <nav className={styles.nav} aria-label="Edition sections"><a href="#lead">The lead</a><a href="#rankings">The 21</a><a href="#morpho">Morpho</a><a href="#circle">Circle / Arc</a><a href="#builders">Builders</a><a href="#partner">Partner space</a></nav>
  <section id="lead" className={styles.lead}><div><p className={styles.eyebrow}>The editorial read / 02 Oct</p><h2>Read the clock.<br/>Then the number.</h2><p>A morning asset price, a closed fund session, a company filing and an afternoon lending rate are different observations. This edition carries the timestamp and evidence class with each one.</p></div><aside><span className={styles.bigNumber}>21</span><p>Our ranking frame. We leave Litecoin positions open when there is no comparable verified entry.</p></aside></section>
  <section id="rankings" className={styles.rankings}><Ranking title="Bitcoin products / 21" rows={products} unit="BTC" href={source.products}/><Ranking title="Public Bitcoin treasuries / 21" rows={btcCompanies} unit="BTC" href={source.btc}/></section>
  <section className={styles.divider}><p>Sound money. Open rails. Source by source.</p></section>
  <section id="morpho" className={styles.desk}><div className={styles.sectionTitle}><p className={styles.eyebrow}>Dedicated market desk / Base</p><h2>Borrow USDC.<br/>Know the collateral.</h2></div><div className={styles.cards}><article><h3>cbLTC / USDC</h3><p className={styles.rate}>6.53% <small>borrow observation</small></p><p>Supply 5.73%; LLTV 62.5%. Afternoon October 2 UI extract. Liquidity fields conflict in the source interface and require reconciliation.</p><a href={source.morphoLtc}>Inspect exact market ↗</a></article><article><h3>cbBTC / USDC</h3><p className={styles.rate}>4.94% <small>borrow observation</small></p><p>Supply 4.44%; LLTV 86%. Variable observations, not fixed offers. Token, oracle, curator and audit mapping need exact deployment checks.</p><a href={source.morphoBtc}>Inspect exact market ↗</a></article></div><p className={styles.note}>No wallet connection or transaction. The PDF gives market IDs, disclosed limitations, wrapper eligibility and audit scope notes.</p></section>
  <section id="circle" className={styles.circle}><p className={styles.eyebrow}>USDC / Circle / Arc</p><h2>The dollar layer has its own clock.</h2><p>Circle introduced Arc as an EVM-compatible stablecoin-focused layer one with planned USDC gas and integrated FX. Its October 1 MiCA consultation post is a separate policy update. Neither establishes a live cbLTC market on Arc.</p><a href={source.circle}>Read Circle’s dated updates ↗</a></section>
  <section id="builders" className={styles.builders}><div><p className={styles.eyebrow}>Protocol and project desks</p><h2>Beyond the price.</h2></div><ul><li>Litecoin Foundation · dated official news</li><li>MWEB · maintenance and incident history</li><li>Bitcoin Core and Lightning · releases</li><li>LitVM and LiteForge · research / testnet labels</li><li>Litecoin Register, mNAV and Timechain · attributed snapshots and gaps</li></ul></section>
  <aside id="partner" className={styles.partner}><div><p>HOUSE PROMOTION / NOT A PAID AD</p><h2>Build the Litecoin ecosystem.</h2><span>Featured: Litecoin Foundation · LitVM · rotating open builders</span></div><a href="https://litecoin.com/news">Explore Foundation updates ↗</a></aside>
  <footer className={styles.footer}><span>LTC / Satnam Satoshi</span><p>Daily research and education. Source dates, data gaps and corrections are in the PDF. Fund holdings, corporate treasuries and wrapped reserves remain separate. <a href={pdf}>Open the complete magazine and sourcebook ↗</a></p><a href="/conversations/">LTC reading room</a></footer>
</main>}