import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { ltcEditions, ltcPublicationDays, formatEditionDate, editionHref, editionDateHref, archiveMonthHref } from '../../../data/editions';
import styles from '../../magazine.module.css';

export const dynamicParams = false;
export function generateStaticParams() { return [...ltcEditions.map(edition => ({ id: edition.id })), ...ltcPublicationDays.map(day => ({ id: day.date }))]; }
function findEdition(id: string) { return ltcPublicationDays.find(day => day.date === id)?.latest ?? ltcEditions.find(edition => edition.id === id); }
export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> {
  const { id } = await params;
  const edition = findEdition(id);
  return edition ? { title: `LTC · ${formatEditionDate(edition.date)} · Daily record`, description: edition.dek } : {};
}
function collectedDate(value: string) {
  return new Intl.DateTimeFormat('en-US', { dateStyle: 'long', timeStyle: 'short', timeZone: 'America/New_York' }).format(new Date(value));
}

export default async function EditionPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const edition = findEdition(id);
  if (!edition) notFound();
  const dayIndex = ltcPublicationDays.findIndex(day => day.date === edition.date);
  const day = ltcPublicationDays[dayIndex];
  const previous = ltcPublicationDays[dayIndex + 1];
  const following = ltcPublicationDays[dayIndex - 1];
  const newer = ltcEditions.filter(item => item.date === edition.date && item.revision > edition.revision);
  return <main className={styles.paper}>
    <nav className={styles.articleNav} aria-label="Magazine navigation"><a className={styles.articleBrand} href="/conversations/" aria-label="LTC magazine home">LTC</a><a href="/conversations/">The reading room</a><a href="/conversations/archive/">Edition archive →</a></nav>
    <header className={styles.editionHeader}><p className={styles.kicker}>LTC Media / {formatEditionDate(edition.date)} / Revision {edition.revision}</p><span className={styles.editionBadge}>{edition.classification}</span><h1>{edition.title}</h1><p className={styles.dek}>{edition.dek}</p><div className={styles.articleMeta}><span>{edition.byline}</span><span>{edition.humanReview}</span><span>Prepared {collectedDate(edition.preparedAt)} · America/New_York</span></div>{newer.length > 0 && <p className={styles.revisionNote}>A later revision exists: <a href={editionHref(newer[0].id)}>read revision {newer[0].revision}</a>. This record remains available for comparison.</p>}</header>
    <nav className={styles.dayNavigation} aria-label="Browse publication days"><div>{previous ? <a href={editionDateHref(previous.date)}><span>← Previous published day</span><strong>{formatEditionDate(previous.date)}</strong></a> : <p><span>The archive begins here</span><strong>{formatEditionDate(edition.date)}</strong></p>}</div><a href={archiveMonthHref(edition.date.slice(0, 7))}>Choose a date</a><div>{following ? <a href={editionDateHref(following.date)}><span>Next published day →</span><strong>{formatEditionDate(following.date)}</strong></a> : <p><span>Latest published day</span><strong>{formatEditionDate(edition.date)}</strong></p>}</div></nav>
    <div className={styles.editionLayout}><article className={styles.editionBody} aria-label="Daily source briefing">{edition.briefs.map((brief, index) => <section className={styles.editionBrief} id={brief.id} key={brief.id}><p className={styles.kicker}>{String(index + 1).padStart(2, '0')} / {brief.desk}</p><h2>{brief.headline}</h2>{brief.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}<p className={styles.meta}>Source-effective date: {brief.effectiveAt}<br/>Evidence: {brief.sourceIds.map((sourceId, sourceIndex) => { const source = edition.sources.find(item => item.id === sourceId)!; return <span key={sourceId}>{sourceIndex > 0 && ' · '}<a href={`#source-${sourceId}`}>{source.title}</a></span>; })}</p></section>)}</article>
    <aside className={styles.editionSidebar} aria-label="Edition reading guide"><p className={styles.kicker}>At this table</p><h2>Read. Check. Question.</h2><ol>{edition.briefs.map(brief => <li key={brief.id}><a href={`#${brief.id}`}>{brief.headline}</a></li>)}</ol><a className={styles.readLink} href="#sourcebook">Inspect the sourcebook</a><a className={styles.readLink} href="#coverage">What is missing?</a><div><h2>New to the subject?</h2><p>Read the date first. A holdings record describes a balance; a software release describes code. Neither establishes a price forecast or network-wide adoption.</p><a className={styles.readLink} href="/sikh-bitcoin/course/foundations/">Start Bitcoin Foundations</a></div><div><h2>Go deeper</h2><p>Keep the exact record, parser version and source hash. Then challenge the assumption behind the headline.</p><a className={styles.readLink} href="/conversations/methodology/">Our research method</a></div></aside></div>
    <section className={styles.editionSources} id="sourcebook" aria-labelledby="sourcebook-title"><div className={styles.sectionHead}><h2 id="sourcebook-title">The sourcebook</h2><p>{edition.sources.length} public sources · Exact retrieval records</p></div><p className={styles.small}>“Collected” identifies parsed source observations. “Reference retrieved” records availability only. The source’s effective date and our collection time are different fields. These are not independently audited metrics.</p><div className={styles.sourceCards}>{edition.sources.map((source, index) => <article className={styles.sourceCard} id={`source-${source.id}`} key={source.id}><p className={styles.kicker}>{String(index + 1).padStart(2, '0')} / {source.kind} source / {source.status.replaceAll('-', ' ')}</p><h3><a className={styles.headlineLink} href={source.url}>{source.title} ↗</a></h3><p>Source-effective date: {source.sourceAsOf ?? 'Not established'}<br/>Collected: {collectedDate(source.checkedAt)} · America/New_York<br/>Freshness at edition preparation: {source.freshness.replaceAll('-', ' ')}</p>{source.observations?.length ? <ul>{source.observations.map(observation => <li key={observation.metric}><strong>{observation.label}:</strong> {observation.value} {observation.unit}<br/><span>Effective {observation.effectiveAt} · {observation.classification.replaceAll('-', ' ')}</span></li>)}</ul> : <p>{source.status === 'unavailable' ? `Collection unavailable${source.httpStatus ? ` (HTTP ${source.httpStatus})` : ''}. No observation is reported.` : 'Page availability only. No numerical metrics were validated from this reference.'}</p>}<details><summary>Technical evidence record</summary><dl><dt>Parser</dt><dd><code>{source.parserVersion}</code></dd><dt>Checked UTC</dt><dd><code>{source.checkedAt}</code></dd><dt>SHA-256</dt><dd><code>{source.sourceSha256 ?? 'No retrieved source hash'}</code></dd>{source.errorCode && <><dt>Failure</dt><dd><code>{source.errorCode}</code></dd></>}</dl></details></article>)}</div><p className={styles.small}><a href={`/data/ltc-editions/${edition.id}.json`}>Download this edition’s JSON record</a> · <a href="/conversations/feed.xml">Follow new editions with RSS</a>. Source hashes identify retrieved bytes; they do not certify a publisher’s claims.</p></section>
    <section className={styles.coverage} id="coverage" aria-labelledby="coverage-title"><p className={styles.kicker}>The reporting still to do</p><h2 id="coverage-title">What this edition does not establish</h2><ul>{edition.coverageGaps.map(gap => <li key={gap}>{gap}</li>)}</ul><p>Missing data is not zero. A dated upstream release can remain the latest returned record for months. We keep its original date rather than relabeling it as today’s announcement.</p></section>
    <section className={styles.editionSources} id="corrections" aria-labelledby="corrections-title"><div className={styles.sectionHead}><h2 id="corrections-title">Corrections & publication record</h2><p>Revision {edition.revision}</p></div>{edition.corrections.length ? <ul>{edition.corrections.map(correction => <li key={correction.correctsEditionId}><a href={editionHref(correction.correctsEditionId)}>{correction.correctsEditionId}</a>: {correction.reason}</li>)}</ul> : <p className={styles.small}>No correction is recorded for this revision. Corrections are published as a new revision; earlier editions remain visible.</p>}<div className={styles.revisionHistory}><p><a href={editionDateHref(edition.date)}>Permanent page for {formatEditionDate(edition.date)}</a> · <a href={editionHref(edition.id)}>Link to this exact revision</a></p><p>The date page shows the latest accepted revision for this day. Exact revision links preserve the earlier record.</p><ul>{day.revisions.map(record => <li key={record.id}><a href={editionHref(record.id)}>Revision {record.revision}</a>{record.id === edition.id ? ' · reading now' : ''}{record.id === day.latest.id ? ' · latest for this date' : ''}</li>)}</ul></div><p className={styles.small}>Edition date: {edition.date} in {edition.timezone}. Preparation: {edition.preparedAt}. Edition release record: {edition.publishedAt}. The release timestamp is recorded by the publishing process, not an independent timestamp authority.</p><p className={styles.small}>Publication follows a source-bound automated briefing policy. Material analysis, opinion and other editorial previews remain labeled for human review. <a href="/conversations/about/">Read the newsroom policy</a>.</p><p className={styles.small}>General education and research, not individualized investment advice. No affiliation with cited organizations is implied. <a href="https://github.com/Satnam-Satoshi/Satoshi-Langar/issues/new?title=LTC%20source%20or%20correction">Report a correction with supporting evidence</a>; public submissions must not contain confidential information.</p></section>
  </main>;
}
