import type { Metadata } from 'next';
import styles from '../magazine.module.css';
export const metadata: Metadata = { title: 'LTC · What mNAV can—and cannot—tell us', description: 'An evidence-led explainer on treasury-company ratios, source dates, dilution, and the LTC editorial method.' };
export default function MethodologyPage() {
  return <main className={styles.paper}><nav className={styles.articleNav} aria-label="Magazine navigation"><a className={styles.articleBrand} href="/conversations/" aria-label="LTC magazine home">LTC</a><a href="/conversations/">Magazine home</a><a href="/conversations/archive/">Archive →</a></nav><header className={styles.articleHeader}><p className={styles.kicker}>Markets &amp; institutions · Founding explainer</p><h1>What mNAV can—and cannot—tell us.</h1><p className={styles.dek}>A ratio becomes useful when you can explain its inputs. Inspect the method before trusting the headline.</p><div className={styles.articleMeta}><span>Prepared with AI for LTC</span><span>First drafted September 30 · Revised October 1, 2026</span><span><strong>Editorial preview · Human editorial review pending</strong></span></div></header>
    <article className={`${styles.articleBody} reading-content magazine-article`}>
      <p className="eyebrow">Educational explainer · Sources checked October 1, 2026 · About 5 minutes</p>
      <h2>Start with a company, not a pile of coins.</h2>
      <p>Owning shares in a company that holds Bitcoin is different from holding Bitcoin. The company has a capital structure, operating activities, costs, and claims ahead of common shareholders. A market-value-to-asset ratio can describe one relationship. It cannot remove these differences.</p>
      <p>“mNAV” is used for several measures. One analyst may compare equity market value with gross cryptocurrency holdings. Another may add debt and preferred claims, subtract selected cash, and compare that enterprise value with the coins. Those are different questions. A chart that hides the formula hides the question.</p>
      <h2>A definition can change while the label stays.</h2>
      <p><a href="https://www.strategy.com/notes">Strategy’s current metric notes</a> document a definition change on July 23, 2026. Its current mNAV compares common share price with net Bitcoin per share in dollars, using its specified treatment of senior claims and dilution. Earlier values are not directly comparable. Any future LTC calculated series must therefore include a methodology version.</p>
      <h2>Read the numerator and denominator.</h2>
      <div className="task-grid"><section className="task-card"><h3>Above the line</h3><p>Which equity value? Which share count and price date? Is debt included? Are preferred securities valued at par, market price, or a liquidation claim?</p></section><section className="task-card"><h3>Below the line</h3><p>Gross coins or net assets? Which price, currency, and time? Which liabilities and cash offsets? Do restricted or receivable assets count?</p></section></div>
      <p>Consider a deliberately simple teaching example: a company valued at $120 with $100 of gross Bitcoin has an equity-to-gross-coins multiple of 1.2. If it also has $30 of specified debt and $10 of cash, an enterprise-value version would be 1.4. These are fictional numbers, not a company valuation or an investment signal. Neither example includes every possible claim or business asset.</p>
      <p>Convertible instruments need particular care: counting converted shares and also deducting the same instrument as debt can double-count a claim. A negative or zero denominator is not a meaningful positive valuation multiple. A low multiple does not establish a bargain; a high multiple does not establish a sound financing strategy.</p>
      <h2>What a useful institutional report must show.</h2>
      <ul><li>Stable entity identity, primary disclosures, and the financial period each fact describes.</li><li>Named formulas, complete inputs, currency, dates, and basic or diluted share treatment.</li><li>Debt, preferred claims, cash offsets, exclusions, and unresolved discrepancies.</li><li>Separate issuer-reported figures from our calculations, estimates, interpretation, and opinion.</li><li>A correction record and an accountable editor, without promising an audit we have not performed.</li></ul>
      <p>LTC is building toward that standard. Today’s website does not calculate a live mNAV, rank investments, or claim audited institutional coverage.</p>
      <section id="freshness"><h2>Two clocks, sometimes four.</h2><p>A record can have a financial period end, publication date, market-price timestamp, and retrieval time. These dates answer different questions. Fetching an old disclosure this morning does not make its holdings current.</p><p>The collector preserves the IBIT CSV’s holdings date and the original release times for Bitcoin Core, Litecoin Core and LND. Other source checks report availability only. If a fetch or parser fails, its observations are null. The snapshot never manufactures a zero, a new source date, or an updated flow.</p><p>Holdings are a stock at a point in time. Net flows describe movement over an interval. A change in fund value can also reflect price, fees, or valuation differences. We will not equate these measures to fill a missing table.</p><p>The current age label uses a conservative four-calendar-day threshold for IBIT, evaluated when collected. An exchange-calendar model, late disclosures, and recurring freshness monitoring remain follow-up work. Always read the effective date, even when the fetch succeeded.</p></section>
      <section id="editorial-standard"><h2>The LTC editorial compact.</h2><ol><li><strong>Reported fact:</strong> identify who reported it and link the record.</li><li><strong>Estimate:</strong> show the calculation, assumptions, and uncertainty.</li><li><strong>Analysis:</strong> explain the inference and credible alternatives.</li><li><strong>Opinion:</strong> name it plainly; do not dress it as neutral fact.</li></ol><p>Political coverage should state the exact action, jurisdiction, date, and status. A proposal, a vote in one chamber, an enacted law, an agency statement, and a court ruling are different things. An accountable human editor must review framing and fairness before an edition is marked reviewed; agents can assist retrieval and comparisons. Community stories require consent.</p><p>Corrections will retain the prior edition reference, changed claim, reason, date, and supporting source. A sponsorship cannot buy a conclusion. We will not publish personal portfolio advice or fabricated daily activity.</p></section>
      <section><h2>Read the primary record.</h2><ul><li><a href="https://www.strategy.com/notes">Strategy: current definitions and limitations</a></li><li><a href="https://www.ishares.com/us/products/333011/ishares-bitcoin-trust-etf">iShares: IBIT product, holdings, valuation notes and prospectus</a></li><li><a href="https://www.sec.gov/search-filings/edgar-application-programming-interfaces">SEC: public filing and XBRL APIs</a></li><li><a href="https://www.congress.gov/">Congress.gov: legislation and official actions</a></li><li><a href="https://github.com/bitcoin/bitcoin/releases">Bitcoin Core: upstream releases</a></li></ul></section>
      <p><a className="launch-button" href="/conversations/">Return to the magazine →</a></p><p className="fine-print">General education and research. This original AI-prepared explainer awaits human editorial review. It is not individualized investment advice, an independent audit, or an endorsement by any cited organization.</p>
    </article>
  </main>;
}
