import type { Metadata } from 'next';
import { propose } from '../../data/ecosystem';
import styles from './about.module.css';

export const metadata: Metadata = {
  title: 'About LTC Media · An open newsroom',
  description: 'Lunch Time Conversations is Satnam Satoshi’s media project: Bitcoin, evidence and service, made understandable. Meet the editorial standard and find a useful first contribution.',
};

const correctionHref = propose('LTC correction: ', 'Article or edition URL:\n\nWhat needs correcting:\n\nPrimary source and its date:\n\nSuggested correction:\n');
const pitchHref = propose('LTC source or story proposal: ', 'The question worth explaining:\n\nWho would this help understand it:\n\nPrimary sources and dates:\n\nWhat remains uncertain:\n\nRelevant interests or affiliations:\n');
const agentRoles = [
  ['Source collector', 'Fetches approved public records and preserves when, where and how they were obtained.'],
  ['Evidence checker', 'Checks source identity, effective dates, units and missing data before a number reaches the page.'],
  ['Data editor', 'Turns accepted observations into a short factual briefing. Keeps estimates and analysis separate.'],
  ['Design & accessibility reviewer', 'Checks reading order, contrast, mobile layouts, keyboard paths and links.'],
  ['Release archivist', 'Checks the edition, keeps its evidence record and records what was published or withheld.'],
  ['Community editor', 'Prepares contribution prompts, translations and corrections for accountable review.'],
];

export default function AboutLtcPage() {
  return <main className={styles.page}>
    <nav className={styles.topbar} aria-label="LTC navigation"><a href="/conversations/" className={styles.wordmark}>LTC</a><span>A Satnam Satoshi media project</span><a href="/conversations/">Read the latest issue ↗</a></nav>
    <header className={styles.hero}><p className={styles.kicker}>About the open newsroom</p><h1>Understand the world.<br/><em>Put that knowledge to work.</em></h1><p className={styles.dek}>Lunch Time Conversations brings Bitcoin, public policy, open technology and service to one table. For the first question. For the deeper rabbit hole. For the work we can do together.</p><div className={styles.actions}><a className={styles.button} href="/conversations/">Open the magazine →</a><a href="/join/?path=ltc">Find a newsroom contribution →</a></div></header>
    <section className={styles.statement} aria-labelledby="standard"><p className={styles.kicker}>Our editorial compass</p><div><h2 id="standard">A Nakamoto standard.<br/>A human purpose.</h2><p>For us, the Nakamoto standard means understandable rules, evidence readers can inspect, open participation and individual sovereignty. Bitcoin’s proof of work anchors that conversation. It is a project commitment, not a new protocol or a claimed endorsement.</p><p>Seva gives knowledge a purpose: help someone learn, create or serve with dignity. AI can make careful work easier; it does not replace human judgment, community consent or responsibility.</p><a href="/technology/">Explore our technology principles →</a></div></section>
    <section aria-labelledby="reading-start"><div className={styles.sectionHead}><p className={styles.kicker}>There is no entrance exam</p><h2 id="reading-start">Two starting points. One open table.</h2></div><div className={styles.paths}><article><span className={styles.pathNumber}>01 · NEW TO BITCOIN</span><h3>Bring your curiosity.</h3><p>Read a briefing, follow an unfamiliar term into a lesson, and ask one good question. You never need to buy bitcoin or connect a wallet to belong here.</p><a href="/sikh-bitcoin/course/foundations/">Start Bitcoin Foundations →</a></article><article><span className={styles.pathNumber}>02 · READY TO GO DEEPER</span><h3>Bring your scrutiny.</h3><p>Inspect sources and methods. Explore consensus and self-custody. Help us improve an explanation so the next reader can check it for themselves.</p><a href="/sikh-bitcoin/course/deep-dive/">Open Bitcoin Deep Dive →</a><a href="/conversations/methodology/">Inspect the research method →</a></article></div></section>
    <section id="editorial-standard" className={styles.standard} aria-labelledby="promise"><div><p className={styles.kicker}>The publishing promise</p><h2 id="promise">Evidence first.<br/>A visible trail after.</h2><p>Each edition identifies its date, evidence and production status. A fresh collection time never makes an old record new. A delayed or withheld release leaves the previous dated issue visible.</p></div><div className={styles.promiseList}><article><h3>A bounded daily briefing</h3><p>Approved public sources supply the factual briefing. Automated checks test source identity, dates and units. Missing information stays missing; a failed check can withhold an item or a release.</p></article><article><h3>Analysis has a different job</h3><p>Interpretation, opinion and original reporting carry their own labels and sources. AI-prepared features remain editorial previews until a human editor records review. Automated checks are not independent human review.</p></article><article><h3>Humans set the boundaries</h3><p>AI Satoshi Ma coordinates research, drafting and checks as the project’s AI editorial lead. The human founder retains publication policy and final authority. Human editorial stewards are still being recruited.</p></article><article><h3>Corrections belong in the record</h3><p>We keep the issue date and explain material corrections. Issuer statements remain attributed; holdings are not flows. Political facts, inference and opinion are separated. General research is not a personalized investment recommendation.</p></article></div></section>
    <section aria-labelledby="agents"><div className={styles.sectionHead}><p className={styles.kicker}>One workflow, distinct responsibilities</p><h2 id="agents">Useful agents. Accountable work.</h2><p>These are workflow roles, not claims of a staffed newsroom or independent organizations. Every run operates within the founder’s rules, with a record of its sources and checks. Publication can be paused.</p></div><div className={styles.agentGrid}>{agentRoles.map(([title, description], index) => <article key={title}><span>{String(index + 1).padStart(2, '0')}</span><h3>{title}</h3><p>{description}</p></article>)}</div><p className={styles.small}><a href="https://github.com/Satnam-Satoshi/Satoshi-Langar/blob/agent/community-ecosystem-20260930/docs/LTC-AGENTS.md">Read the agent charters on GitHub ↗</a> · <a href="/agents/">Build with Agent Sangat →</a></p></section>
    <section className={styles.contribute} aria-labelledby="contribute"><div><p className={styles.kicker}>Your first useful contribution</p><h2 id="contribute">A good question<br/>can open a door.</h2><p>Choose one source check, explanation, translation or accessibility improvement. Small, reviewable work helps this publication grow across languages and time zones.</p><a className={styles.button} href="/join/?path=ltc">Make a guest contribution plan →</a></div><ol><li><strong>Choose a question.</strong><p>Point to a story or a gap. Say who it would help.</p></li><li><strong>Bring the evidence.</strong><p>Include a primary source, its date and anything you could not verify.</p></li><li><strong>Share a public proposal.</strong><p>A GitHub account is needed to submit an issue. You can prepare your plan as a guest first. Proposals need review; no assignment or reply time is promised.</p></li></ol></section>
    <section className={styles.serviceLinks} aria-label="Follow and improve LTC"><article><p className={styles.kicker}>Follow the publication</p><h2>Your reading habit.<br/>Your choice of reader.</h2><p>Add our RSS feed URL to a feed reader, or browse the dated archive. Reading does not require a mailing-list signup.</p><a href="/conversations/feed.xml">Open the RSS feed →</a><a href="/conversations/archive/">Browse the archive →</a></article><article><p className={styles.kicker}>Keep the record honest</p><h2>Have a source<br/>or a correction?</h2><p>Open a prepared GitHub draft. It becomes public when you submit it: leave out private contact details, beneficiary records, financial information and secrets.</p><a href={correctionHref}>Prepare a correction ↗</a><a href={pitchHref}>Pitch a source or story ↗</a></article></section>
    <footer className={styles.note}><p>LTC Media is the media project of Satnam Satoshi. This description does not claim company incorporation, charity registration, affiliation with named publishers or a legally established trust.</p><p><a href="/conversations/methodology/">Research methodology</a> · <a href="/privacy/">Privacy</a> · <a href="/transparency/">Project transparency</a> · <a href="/connect/">Community channels</a></p></footer>
  </main>;
}
