import { octoberSixExtra, newsExtraHref } from '../../data/news-extra';
import {editorialSpecials,specialHref} from '../../data/editorial-specials';
import { magazineArticles, articleHref, magazineIssue } from '../../data/magazine';
import { ltcEditions, editionHref, formatEditionDate } from '../../data/editions';
import { publicationUpdates } from '../../data/edition-calendar';
export const dynamic = 'force-static';
const canonicalBase = 'https://https-github-com-satnam-satoshi-sat.vercel.app';
const escapeXml = (value: string) => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&apos;');
export function GET() {
  const updates = publicationUpdates(ltcEditions);
  const newestDate=[octoberSixExtra.preparedAt,...updates.map(e=>e.publishedAt),...editorialSpecials.map(e=>e.preparedAt)].sort((a,b)=>Date.parse(b)-Date.parse(a))[0];
  const editions = updates.map(edition => `<item><title>${escapeXml(`${formatEditionDate(edition.date)} — ${edition.title} (r${edition.revision})`)}</title><link>${canonicalBase}${editionHref(edition.id)}</link><guid isPermaLink="false">ltc:edition:${edition.id}</guid><pubDate>${new Date(edition.publishedAt).toUTCString()}</pubDate><description>${escapeXml(`${edition.dek} ${edition.byline}. ${edition.humanReview}. Source dates, missing coverage and corrections appear with the edition.`)}</description><category>Automated source briefing</category></item>`).join('');
  const specials=editorialSpecials.map(s=>`<item><title>${escapeXml(`[Special edition] ${s.subject}: ${s.title}`)}</title><link>https://ltcmagazine.org${specialHref(s.slug)}</link><guid isPermaLink="false">ltc:special:${s.id}</guid><pubDate>${new Date(s.preparedAt).toUTCString()}</pubDate><description>${escapeXml(`${s.dek} AI-prepared historical feature; research through ${s.researchThrough}. Sources and limits accompany each chapter.`)}</description><category>Special edition</category></item>`).join('');
  const extra = `<item><title>${escapeXml(`[October 6 news extra] ${octoberSixExtra.title}`)}</title><link>https://ltcmagazine.org${newsExtraHref}</link><guid isPermaLink="false">ltc:extra:${octoberSixExtra.id}</guid><pubDate>${new Date(octoberSixExtra.preparedAt).toUTCString()}</pubDate><description>${escapeXml(`${octoberSixExtra.dek} ${octoberSixExtra.review}`)}</description><category>News extra</category></item>`;
  const previews = [...magazineArticles].reverse().map(article => `<item><title>${escapeXml(`[Editorial preview] ${article.title}`)}</title><link>${canonicalBase}${articleHref(article.slug)}</link><guid isPermaLink="false">${escapeXml(article.preparedDate ? `ltc:feature:${article.slug}:preview-v1` : `ltc:${magazineIssue.id}:${articleHref(article.slug)}:preview-v1`)}</guid><description>${escapeXml(`${article.dek} Prepared with AI. Human editorial review pending. Sources checked ${article.sourceCheckedDate ?? magazineIssue.date}. This is an editorial preview, separate from the automated source briefings.`)}</description><category>${escapeXml(article.desk)}</category></item>`).join('');
  const methodology = `<item><title>${escapeXml('[Editorial preview] What mNAV can—and cannot—tell us.')}</title><link>${canonicalBase}/conversations/methodology/</link><guid isPermaLink="false">${escapeXml(`ltc:${magazineIssue.id}:/conversations/methodology/:preview-v1`)}</guid><description>A founding AI-prepared explainer on company ratios, source dates, debt and dilution. Human editorial review pending.</description><category>Markets &amp; institutions</category></item>`;
  const xml = `<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>LTC Media — Lunch Time Conversations</title><link>${canonicalBase}/conversations/</link><description>Dated AI-prepared source briefings and original editorial previews from LTC Media. Source dates, coverage limits and human-review status remain visible.</description><language>en</language><atom:link href="${canonicalBase}/conversations/feed.xml" rel="self" type="application/rss+xml"/>${newestDate ? `<lastBuildDate>${new Date(newestDate).toUTCString()}</lastBuildDate>` : ''}${extra}${specials}${editions}${previews}${methodology}</channel></rss>`;
  return new Response(xml, { headers: { 'Content-Type': 'application/rss+xml; charset=utf-8' } });
}
