import type { Metadata } from 'next';
import {communityArchive,communityArchiveHref,communityDate,communityDirectory,selectedCommunityReading} from '../../data/community-wire';
import styles from './wire.module.css';

export const metadata:Metadata={title:'Litecoin Community Wire · Builders, sources & learning',description:'A curated Litecoin reading room: Foundation and developer records, LitVM, Nexus, public community profiles and a permanent dated source-check archive.'};
export default function CommunityWire(){
 const newest=communityArchive[0];
 return <main className={styles.page}>
 <header className={styles.hero}><div><p className={styles.kicker}>LTC / The community wire</p><h1>Many voices.<br/><em>One open<br/>conversation.</em></h1><p className={styles.dek}>Meet the people. Follow the source. Understand what changed.</p><p>Litecoin is more than a ticker. This is a reading room for its builders, learners and long memory—with Bitcoin as a companion in the conversation.</p><nav className={styles.actions} aria-label="Community Wire sections"><a href="#records">Project records ↓</a><a href="#reading">Editor’s reading table ↓</a><a href="#directory">The community directory ↓</a><a href="#history">Keep the history ↓</a></nav></div><div className={styles.art} role="img" aria-label="An original diagram of connected voices around Litecoin, with a Bitcoin thread. This is conceptual art, not a network chart."><span className={styles.orbit}/><span className={styles.core}>Ł</span><span className={styles.bitcoin}>₿</span><span className={styles.voice1}>BUILD</span><span className={styles.voice2}>LEARN</span><span className={styles.voice3}>VERIFY</span><span className={styles.voice4}>SHARE</span><p>OPEN MONEY.<br/><em>HUMAN STORIES.</em></p></div></header>
 <div className={styles.status}><strong>Curated. Attributed. Dated.</strong><p>Reviewed source links and official release records—not an unfiltered social feed. X timeline ingestion is not connected. Account links below open on X; they do not imply partnership or endorsement.</p></div>
 <section id="records" className={styles.section}><header className={styles.sectionHead}><div><p className={styles.kicker}>The latest accepted source check</p><h2>From the builders.</h2></div><p>Collected <time dateTime={newest.snapshot.collectedAt}>{newest.snapshot.collectedAt}</time><br/>Publication dates remain unchanged.</p></header><div className={styles.recordGrid}>{newest.snapshot.items.map(item=><article key={item.id}><span className={styles.kicker}>{item.sourceName}</span><h3><a href={item.url}>{item.title} ↗</a></h3><p className={styles.date}>Originally published <time dateTime={item.publishedAt}>{communityDate(item.publishedAt)}</time></p><p>A first-party project record. A new check does not make an old announcement new, and an announcement does not establish independently tested behavior.</p><a href={communityArchiveHref(newest.id)}>Inspect the saved source check →</a></article>)}<aside className={styles.sourceState}><h3>A visible gap is useful information.</h3>{newest.snapshot.sourceStatus.map(source=><div key={source.id}><a href={source.id==='litecoin-foundation-news'?'https://litecoin.com/news':source.url}>{source.sourceName} ↗</a><p>{source.status==='collected'?'Source record collected.':'No accepted feed record in this check.'}<br/>{source.checkedAt?<time dateTime={source.checkedAt}>Checked {source.checkedAt}</time>:'Not requested in this check.'}</p></div>)}<a href="/conversations/updates/">Open the wider data notebook →</a></aside></div></section>
 <section id="reading" className={styles.section}><header className={styles.sectionHead}><div><p className={styles.kicker}>Selected October 5, 2026 / Original source dates below</p><h2>A little context.<br/><em>A longer view.</em></h2></div><p>AI Satoshi Ma’s source-linked reading selections. Original summaries of first-party announcements, not independent reporting or newly published news.</p></header><div className={styles.readingGrid}>{selectedCommunityReading.map((item,index)=><article key={item.id} className={styles.readingCard}><div className={styles.cardArt} data-art={index}><span aria-hidden="true">{item.mark}</span><p>{['A ROADMAP IS A PLAN.','MAKE MONEY USEFUL.','EXPERIMENT. CHECK. REPEAT.','MEMORY IS A COMMON GOOD.'][index]}</p></div><div className={styles.cardBody}><p className={styles.kicker}>{item.label} / {item.source}</p><p className={styles.date}>Source published <time dateTime={item.date}>{communityDate(item.date)}</time></p><h3>{item.title}</h3><p>{item.summary}</p><details><summary>What this source does—and does not—establish</summary><p>{item.limit}</p></details><a href={item.url}>Read the original source ↗</a><a href={item.learn}>{item.learnLabel} →</a></div></article>)}</div></section>
 <section className={styles.explainer} aria-labelledby="editorial-title"><p className={styles.kicker}>Before something reaches this page</p><h2 id="editorial-title">Worth sharing?<br/><em>Show your work.</em></h2><ol><li><strong>Who said it?</strong><p>Check the source identity and link to the original. A requested account is a lead, not automatic authority.</p></li><li><strong>When did it happen?</strong><p>Keep the event, publication and collection dates separate. Old stories can teach without pretending to be new.</p></li><li><strong>What does it establish?</strong><p>Label releases, announcements and opinions. Follow material claims into code, official records or documentation.</p></li><li><strong>Why will it help?</strong><p>Add an understandable explanation, a useful learning path and a way to correct the record. Leave repetition and unsupported claims out.</p></li></ol><a href="/conversations/about/#editorial-standard">Read our editorial commitments →</a></section>
 <section id="directory" className={styles.section}><header className={styles.sectionHead}><div><p className={styles.kicker}>The founder’s 13-account reading list</p><h2>Meet the conversation.</h2></div><p>Independent people and projects. These are source-discovery links, not a roster of contributors or verified endorsements. Current account ownership is not confirmed for every entry.</p></header><div className={styles.directory}>{communityDirectory.map(person=><article key={person.handle}><p className={styles.kicker}>{person.desk}</p><h3>{person.name}</h3><p>{person.why}</p><a href={`https://x.com/${person.handle}`}>@{person.handle} on X ↗</a><a href={person.source}>Project or identity reference ↗</a></article>)}</div></section>
 <section id="history" className={styles.section}><header className={styles.sectionHead}><div><p className={styles.kicker}>The living archive</p><h2>New chapters.<br/><em>Old pages kept.</em></h2></div><p>Each source check has a permanent record. The daily magazine, community notebook and project story each keep their own dates.</p></header><div className={styles.history}>{communityArchive.map(record=><a key={record.id} href={communityArchiveHref(record.id)}><span>Source check</span><strong>{record.snapshot.collectedAt}</strong><span>{record.snapshot.items.length} accepted {record.snapshot.items.length===1?'record':'records'} →</span></a>)}</div><div className={styles.actions}><a href="/conversations/archive/">Every edition + special →</a><a href="/mission/">The Satnam Satoshi story →</a><a href="/sikh-bitcoin/">Start a learning path →</a></div></section>
 <aside className={styles.invitation}><p className={styles.kicker}>A source is a contribution</p><h2>Bring the next<br/><em>good question.</em></h2><p>Have a useful public post, release or correction? Include its original link and date, what it helps explain, and what remains uncertain. Our review happens before publication.</p><div className={styles.actions}><a href="https://github.com/Satnam-Satoshi/Satoshi-Langar/issues/new?title=LTC%20Community%20Wire%20source&body=Original%20public%20URL%3A%0ASource%20date%3A%0AWhy%20it%20matters%3A%0AWhat%20needs%20checking%3A">Propose a source on GitHub ↗</a><a href="/join/?path=ltc">Plan a newsroom contribution →</a></div><p className={styles.small}>GitHub proposals are public when you submit them. Leave out private messages, contact records and secrets.</p></aside>
 </main>;
}
