import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { courses, getCourseLessons } from '../../../data/courses';
import { LearningProgress } from '../../components/LearningProgress';
import {CourseVisual,LearningSubnav,chapters,courseStyle} from '../../components/LearningVisuals';
import s from '../../learning.module.css';
type Props={params:Promise<{courseId:string}>};
export const dynamicParams=false;
export function generateStaticParams(){return courses.map(({id})=>({courseId:id}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {courseId}=await params;const c=courses.find(c=>c.id===courseId);if(!c)notFound();return{title:`${c.title} · Sikh Bitcoin`,description:c.description}}
export default async function CoursePage({params}:Props){const {courseId}=await params;const c=courses.find(c=>c.id===courseId);if(!c)notFound();const ls=getCourseLessons(c.id);return <main className={s.school}><div className={s.wrap}><LearningSubnav/><section className={s.courseHero}><div><span className={s.eyebrow}>{c.level} / 21 lessons / {courseStyle[c.id].verb}</span><h1>{c.title}</h1><p>{c.description.replace('and Bitcoin maxis ','')}</p><div className={s.actions}><a className={s.button} href={`/sikh-bitcoin/${ls[0].slug}/`}>Start lesson 1 →</a><a className={s.secondary} href={`/sikh-bitcoin/lab/#${courseStyle[c.id].lab}`}>Try a practice challenge ↗</a></div><p className={s.note}>{c.duration}. {c.prerequisite}</p></div><CourseVisual id={c.id}/></section><div className={s.outcomes}><h2 className={s.eyebrow}>What you’ll take away</h2><p>{c.outcome}</p></div><LearningProgress course={c} lessons={ls}/><section className={s.section} aria-labelledby="course-contents"><div className={s.sectionHead}><div><span className={s.eyebrow}>Your course map</span><h2 id="course-contents">Three chapters.<br/>Twenty-one new perspectives.</h2></div><p>Follow the path or jump to a question. No lesson is locked. Finish with a capstone you can explain to a friend.</p></div><nav className={s.chapterNav} aria-label="Course chapters">{chapters[c.id].map((ch,i)=><a key={ch.title} href={`#chapter-${i+1}`}>0{i+1} / {ch.title}</a>)}</nav>{chapters[c.id].map((ch,i)=><section id={`chapter-${i+1}`} className={s.chapter} key={ch.title}><header className={s.chapterHeader}><b aria-hidden="true">0{i+1}</b><div><h2>{ch.title}</h2><p>{ch.note}</p></div></header><div className={s.lessonGrid}>{ls.slice(i*7,i*7+7).map(l=><a className={s.lessonCard} href={`/sikh-bitcoin/${l.slug}/`} key={l.slug} data-learning-lesson-link={l.slug}><span className={s.lessonNumber}>{String(l.order).padStart(2,'0')}</span><div><h3>{l.title}</h3><p>{l.description}</p><small>{l.minutes} MIN WITH PRACTICE <span data-learning-completed={l.slug} hidden> · COMPLETE</span></small></div><span aria-hidden="true">↗</span></a>)}</div></section>)}</section><p className={s.note}>AI-assisted material · Lesson sources checked October 1, 2026. Independent curriculum review is pending. All progress is self-reported practice, not a credential. No real funds, recovery words or transactions are needed.</p><div className={s.actions}><a className={s.secondary} href="/sikh-bitcoin/">← All learning paths</a><a className={s.secondary} href="/ecosystem/#ask-ma">Find a source-linked guide →</a></div><div className={s.section}/></div></main>}
